/* eslint-disable */
/* THIS FILE IS AUTOMATICALLY GENERATED */
import ManualSplit from "./Misc/Hornet.png";
import StartNewGame from "./Misc/Hornet.png";
import Act1Start from "./Misc/Hornet.png";
import EndingSplit from "./Boss/GrandMotherSilk.png";
import EndingA from "./Boss/GrandMotherSilk.png";
import Menu from "./Item/Map.png";
import PlayerDeath from "./Misc/Hornet.png";
import AnyTransition from "./Misc/Hornet.png";
import MossMother from "./Boss/MossMother.png";
import MossMotherTrans from "./Boss/MossMother.png";
import SilkSpear from "./Skill/SilkSpear.png";
import SilkSpearTrans from "./Skill/SilkSpear.png";
import BellBeast from "./Boss/BellBeast.png";
import BellBeastTrans from "./Boss/BellBeast.png";
import MarrowBell from "./Misc/Bell.png";
import SwiftStep from "./Skill/SwiftStep.png";
import SwiftStepTrans from "./Skill/SwiftStep.png";
import Lace1 from "./Boss/Lace.png";
import Lace1Trans from "./Boss/Lace.png";
import DeepDocksBell from "./Misc/Bell.png";
import EnterWormways from "./Enemy/Grom.png";
import EnterFarFields from "./Enemy/Fertid.png";
import DriftersCloak from "./Skill/DriftersCloak.png";
import DriftersCloakTrans from "./Skill/DriftersCloak.png";
import FourthChorus from "./Boss/FourthChorus.png";
import EnterGreymoor from "./Enemy/Craw.png";
import GreymoorBell from "./Misc/Bell.png";
import Moorwing from "./Boss/Moorwing.png";
import MoorwingTrans from "./Boss/Moorwing.png";
import EnterShellwood from "./Enemy/Phacia.png";
import ClingGrip from "./Skill/ClingGrip.png";
import ClingGripTrans from "./Skill/ClingGrip.png";
import ShellwoodBell from "./Misc/Bell.png";
import EnterBellhart from "./Enemy/Furm.png";
import Widow from "./Boss/Widow.png";
import BellhartBell from "./Misc/Bell.png";
import LastJudge from "./Boss/LastJudge.png";
import EnterMist from "./Enemy/Wraith.png";
import LeaveMist from "./Enemy/Wraith.png";
import Phantom from "./Boss/Phantom.png";
import Act2Started from "./Event/Act2Started.png";
import CogworkDancers from "./Boss/CogworkDancers.png";
import WhisperingVaultsArena from "./Enemy/Vaultkeeper.png";
import Trobbio from "./Boss/Trobbio.png";
import TrobbioTrans from "./Boss/Trobbio.png";
import Clawline from "./Skill/Clawline.png";
import EnterHighHalls from "./Enemy/Minister.png";
import EnterHighHallsArena from "./Enemy/Maestro.png";
import HighHallsArena from "./Enemy/ChoirClapper.png";
import Lace2 from "./Boss/Lace.png";
import VaultkeepersMelody from "./Melody/VaultkeepersMelody.png";
import VaultkeepersMelodyTrans from "./Melody/VaultkeepersMelody.png";
import ArchitectsMelody from "./Melody/ArchitectsMelody.png";
import ArchitectsMelodyTrans from "./Melody/ArchitectsMelody.png";
import ConductorsMelody from "./Melody/ConductorsMelody.png";
import ConductorsMelodyTrans from "./Melody/ConductorsMelody.png";
import UnlockedMelodyLift from "./Event/UnlockedMelodyLift.png";
import NeedleUpgrade1 from "./Item/Needle1.png";
import NeedleUpgrade2 from "./Item/Needle2.png";
import NeedleUpgrade3 from "./Item/Needle3.png";
import NeedleUpgrade4 from "./Item/Needle4.png";
import ReaperCrestTrans from "./Crest/Reaper.png";
import SavedFleaHuntersMarch from "./NPC/Flea.png";
import SavedFleaBellhart from "./NPC/Flea.png";
import SavedFleaMarrow from "./NPC/Flea.png";
import SavedFleaDeepDocksSprint from "./NPC/Flea.png";
import SavedFleaFarFieldsPilgrimsRest from "./NPC/Flea.png";
import SavedFleaFarFieldsTrap from "./NPC/Flea.png";
import SavedFleaSandsOfKarak from "./NPC/Flea.png";
import SavedFleaBlastedSteps from "./NPC/Flea.png";
import SavedFleaWormways from "./NPC/Flea.png";
import SavedFleaDeepDocksArena from "./NPC/Flea.png";
import SavedFleaDeepDocksBellway from "./NPC/Flea.png";
import SavedFleaBilewaterOrgan from "./NPC/Flea.png";
import SavedFleaSinnersRoad from "./NPC/Flea.png";
import SavedFleaGreymoorRoof from "./NPC/Flea.png";
import SavedFleaGreymoorLake from "./NPC/Flea.png";
import SavedFleaWhisperingVaults from "./NPC/Flea.png";
import SavedFleaSongclave from "./NPC/Flea.png";
import SavedFleaMountFay from "./NPC/Flea.png";
import SavedFleaBilewaterTrap from "./NPC/Flea.png";
import SavedFleaBilewaterThieves from "./NPC/Flea.png";
import SavedFleaShellwood from "./NPC/Flea.png";
import SavedFleaSlabBellway from "./NPC/Flea.png";
import SavedFleaSlabCage from "./NPC/Flea.png";
import SavedFleaChoralChambersWind from "./NPC/Flea.png";
import SavedFleaChoralChambersCage from "./NPC/Flea.png";
import SavedFleaUnderworksCauldron from "./NPC/Flea.png";
import SavedFleaUnderworksWispThicket from "./NPC/Flea.png";
import SavedFleaGiantFlea from "./NPC/Flea.png";
import SavedFleaVog from "./NPC/Flea.png";
import SavedFleaKratt from "./NPC/Flea.png";
import PutrifiedDuctsStation from "./Misc/Bellway.png";
import BellhartStation from "./Misc/Bellway.png";
import FarFieldsStation from "./Misc/Bellway.png";
import GrandBellwayStation from "./Misc/Bellway.png";
import BlastedStepsStation from "./Misc/Bellway.png";
import DeepDocksStation from "./Misc/Bellway.png";
import GreymoorStation from "./Misc/Bellway.png";
import SlabStation from "./Misc/Bellway.png";
import BilewaterStation from "./Misc/Bellway.png";
import ShellwoodStation from "./Misc/Bellway.png";
import ChoralChambersTube from "./Misc/Ventrica.png";
import UnderworksTube from "./Misc/Ventrica.png";
import GrandBellwayTube from "./Misc/Ventrica.png";
import HighHallsTube from "./Misc/Ventrica.png";
import SongclaveTube from "./Misc/Ventrica.png";
import MemoriumTube from "./Misc/Ventrica.png";
import SeenShakraBonebottom from "./NPC/Shakra.png";
import SeenShakraMarrow from "./NPC/Shakra.png";
import SeenShakraDeepDocks from "./NPC/Shakra.png";
import SeenShakraFarFields from "./NPC/Shakra.png";
import SeenShakraWormways from "./NPC/Shakra.png";
import SeenShakraGreymoor from "./NPC/Shakra.png";
import SeenShakraBellhart from "./NPC/Shakra.png";
import SeenShakraShellwood from "./NPC/Shakra.png";
import SeenShakraHuntersMarch from "./NPC/Shakra.png";
import SeenShakraBlastedSteps from "./NPC/Shakra.png";
import SeenShakraSinnersRoad from "./NPC/Shakra.png";
import SeenShakraMountFay from "./NPC/Shakra.png";
import SeenShakraBilewater from "./NPC/Shakra.png";
import SeenShakraSandsOfKarak from "./NPC/Shakra.png";
import MetJubilanaEnclave from "./NPC/Jubilana.png";
import MetShermaEnclave from "./NPC/Sherma.png";
import UnlockedPrinceCage from "./NPC/GreenPrince.png";
import GreenPrinceInVerdania from "./NPC/GreenPrince.png";
import SeenFleatopiaEmpty from "./NPC/Mooshka.png";
import FaydownCloak from "./Skill/FaydownCloak.png";
import SilkSoar from "./Skill/SilkSoar.png";
import HeartNyleth from "./Item/PollenHeart.png";
import HeartKhann from "./Item/EncrustedHeart.png";
import HeartKarmelita from "./Item/HuntersHeart.png";
import HeartClover from "./Item/ConjoinedHeart.png";
import RedMemory from "./Item/Everbloom.png";
import BellhouseKeyConversation from "./Item/BellhomeKey.png";
import VerdaniaOrbsCollected from "./Enemy/Verdanir.png";
import Forebrothers from "./Boss/Forebrothers.png";
import Groal from "./Boss/Groal.png";
import Conchflies1 from "./Boss/Conchfly.png";
import SavageBeastfly1 from "./Boss/SavageBeastfly.png";
import SavageBeastfly2 from "./Boss/SavageBeastfly.png";
import CaravanTroupeGreymoor from "./NPC/Mooshka.png";
import CaravanTroupeFleatopia from "./NPC/Mooshka.png";
import SoldRelic from "./NPC/Scrounge.png";
import CollectedWhiteWardKey from "./Item/CollectedWhiteWardKey.png";
import PavoTimePassed from "./NPC/Pavo.png";
import SongclaveBell from "./Misc/Bell.png";
import Voltvyrm from "./Boss/Voltvyrm.png";
import SkullTyrant1 from "./Boss/SkullTyrant.png";
import ShermaReturned from "./NPC/Sherma.png";
import JubilanaRescuedMemorium from "./NPC/Jubilana.png";
import JubilanaRescuedChoralChambers from "./NPC/Jubilana.png";
import SilkAndSoulOffered from "./Event/SilkAndSoul.png";
import SoulSnareReady from "./Event/SilkAndSoul.png";
import Seth from "./Boss/Seth.png";
import AbyssEscape from "./Event/Act3Started.png";
import BallowMoved from "./NPC/Ballow.png";
import Act3Started from "./Event/Act3Started.png";
import SisteroftheVoid from "./Achievement/SisteroftheVoid.png";
export default {
  ManualSplit,
  StartNewGame,
  Act1Start,
  EndingSplit,
  EndingA,
  Menu,
  PlayerDeath,
  AnyTransition,
  MossMother,
  MossMotherTrans,
  SilkSpear,
  SilkSpearTrans,
  BellBeast,
  BellBeastTrans,
  MarrowBell,
  SwiftStep,
  SwiftStepTrans,
  Lace1,
  Lace1Trans,
  DeepDocksBell,
  EnterWormways,
  EnterFarFields,
  DriftersCloak,
  DriftersCloakTrans,
  FourthChorus,
  EnterGreymoor,
  GreymoorBell,
  Moorwing,
  MoorwingTrans,
  EnterShellwood,
  ClingGrip,
  ClingGripTrans,
  ShellwoodBell,
  EnterBellhart,
  Widow,
  BellhartBell,
  LastJudge,
  EnterMist,
  LeaveMist,
  Phantom,
  Act2Started,
  CogworkDancers,
  WhisperingVaultsArena,
  Trobbio,
  TrobbioTrans,
  Clawline,
  EnterHighHalls,
  EnterHighHallsArena,
  HighHallsArena,
  Lace2,
  VaultkeepersMelody,
  VaultkeepersMelodyTrans,
  ArchitectsMelody,
  ArchitectsMelodyTrans,
  ConductorsMelody,
  ConductorsMelodyTrans,
  UnlockedMelodyLift,
  NeedleUpgrade1,
  NeedleUpgrade2,
  NeedleUpgrade3,
  NeedleUpgrade4,
  ReaperCrestTrans,
  SavedFleaHuntersMarch,
  SavedFleaBellhart,
  SavedFleaMarrow,
  SavedFleaDeepDocksSprint,
  SavedFleaFarFieldsPilgrimsRest,
  SavedFleaFarFieldsTrap,
  SavedFleaSandsOfKarak,
  SavedFleaBlastedSteps,
  SavedFleaWormways,
  SavedFleaDeepDocksArena,
  SavedFleaDeepDocksBellway,
  SavedFleaBilewaterOrgan,
  SavedFleaSinnersRoad,
  SavedFleaGreymoorRoof,
  SavedFleaGreymoorLake,
  SavedFleaWhisperingVaults,
  SavedFleaSongclave,
  SavedFleaMountFay,
  SavedFleaBilewaterTrap,
  SavedFleaBilewaterThieves,
  SavedFleaShellwood,
  SavedFleaSlabBellway,
  SavedFleaSlabCage,
  SavedFleaChoralChambersWind,
  SavedFleaChoralChambersCage,
  SavedFleaUnderworksCauldron,
  SavedFleaUnderworksWispThicket,
  SavedFleaGiantFlea,
  SavedFleaVog,
  SavedFleaKratt,
  PutrifiedDuctsStation,
  BellhartStation,
  FarFieldsStation,
  GrandBellwayStation,
  BlastedStepsStation,
  DeepDocksStation,
  GreymoorStation,
  SlabStation,
  BilewaterStation,
  ShellwoodStation,
  ChoralChambersTube,
  UnderworksTube,
  GrandBellwayTube,
  HighHallsTube,
  SongclaveTube,
  MemoriumTube,
  SeenShakraBonebottom,
  SeenShakraMarrow,
  SeenShakraDeepDocks,
  SeenShakraFarFields,
  SeenShakraWormways,
  SeenShakraGreymoor,
  SeenShakraBellhart,
  SeenShakraShellwood,
  SeenShakraHuntersMarch,
  SeenShakraBlastedSteps,
  SeenShakraSinnersRoad,
  SeenShakraMountFay,
  SeenShakraBilewater,
  SeenShakraSandsOfKarak,
  MetJubilanaEnclave,
  MetShermaEnclave,
  UnlockedPrinceCage,
  GreenPrinceInVerdania,
  SeenFleatopiaEmpty,
  FaydownCloak,
  SilkSoar,
  HeartNyleth,
  HeartKhann,
  HeartKarmelita,
  HeartClover,
  RedMemory,
  BellhouseKeyConversation,
  VerdaniaOrbsCollected,
  Forebrothers,
  Groal,
  Conchflies1,
  SavageBeastfly1,
  SavageBeastfly2,
  CaravanTroupeGreymoor,
  CaravanTroupeFleatopia,
  SoldRelic,
  CollectedWhiteWardKey,
  PavoTimePassed,
  SongclaveBell,
  Voltvyrm,
  SkullTyrant1,
  ShermaReturned,
  JubilanaRescuedMemorium,
  JubilanaRescuedChoralChambers,
  SilkAndSoulOffered,
  SoulSnareReady,
  Seth,
  AbyssEscape,
  BallowMoved,
  Act3Started,
  SisteroftheVoid,
};
