/* eslint-disable */
/* THIS FILE IS AUTOMATICALLY GENERATED */
import ManualSplit from "./Misc/Hornet.png";
import StartNewGame from "./Misc/Hornet.png";
import Act1Start from "./Misc/Hornet.png";
import EndingSplit from "./Boss/GrandMotherSilk.png";
import EndingA from "./Boss/GrandMotherSilk.png";
import Menu from "./Item/Map.png";
import BenchAny from "./Misc/Bench.png";
import PlayerDeath from "./Misc/Hornet.png";
import AnyTransition from "./Misc/Hornet.png";
import TransitionExcludingDiscontinuities from "./Misc/Hornet.png";
import MossMother from "./Boss/MossMother.png";
import MossMotherTrans from "./Boss/MossMother.png";
import EnterBoneBottom from "./NPC/Pebb.png";
import EnterMosshome from "./Enemy/OvergrownPilgrim.png";
import SilkSpear from "./Skill/SilkSpear.png";
import SilkSpearTrans from "./Skill/SilkSpear.png";
import BoneBottomSimpleKey from "./Item/SimpleKey.png";
import EnterWeavenestAtla from "./Enemy/ServitorIgnim.png";
import BellBeast from "./Boss/BellBeast.png";
import BellBeastTrans from "./Boss/BellBeast.png";
import MarrowBell from "./Misc/Bell.png";
import SwiftStep from "./Skill/SwiftStep.png";
import SwiftStepTrans from "./Skill/SwiftStep.png";
import Lace1 from "./Boss/Lace.png";
import Lace1Trans from "./Boss/Lace.png";
import DeepDocksBell from "./Misc/Bell.png";
import EnterWormways from "./Enemy/Grom.png";
import EnterUpperWormways from "./Enemy/Gromling.png";
import Sharpdart from "./Skill/Sharpdart.png";
import SharpdartTrans from "./Skill/Sharpdart.png";
import EnterHuntersMarch from "./Enemy/Skarrlid.png";
import HuntersMarchPostMiddleArenaTransition from "./Enemy/SkarrScout.png";
import EnterFarFields from "./Enemy/Fertid.png";
import DriftersCloak from "./Skill/DriftersCloak.png";
import DriftersCloakTrans from "./Skill/DriftersCloak.png";
import FourthChorus from "./Boss/FourthChorus.png";
import GurrTheOutcastEncountered from "./Boss/GurrTheOutcast.png";
import GurrTheOutcast from "./Boss/GurrTheOutcast.png";
import EnterGreymoor from "./Enemy/Craw.png";
import GreymoorBell from "./Misc/Bell.png";
import Moorwing from "./Boss/Moorwing.png";
import MoorwingTrans from "./Boss/Moorwing.png";
import ThreadStorm from "./Skill/ThreadStorm.png";
import ThreadStormTrans from "./Skill/ThreadStorm.png";
import EnterHalfwayHomeBasement from "./Enemy/SkarrStalker.png";
import YarnabySlap from "./NPC/Yarnaby.png";
import Crawfather from "./Boss/Crawfather.png";
import EnterWispThicket from "./Enemy/Wisp.png";
import EnterFatherOfTheFlame from "./Boss/FatherOfTheFlame.png";
import FatherOfTheFlame from "./Boss/FatherOfTheFlame.png";
import EnterShellwood from "./Enemy/Phacia.png";
import ClingGrip from "./Skill/ClingGrip.png";
import ClingGripTrans from "./Skill/ClingGrip.png";
import ShellwoodBell from "./Misc/Bell.png";
import EnterBellhart from "./Enemy/Furm.png";
import WidowEncountered from "./Boss/Widow.png";
import Widow from "./Boss/Widow.png";
import MenuNeedolinMemory from "./Skill/Needolin.png";
import BellhartBell from "./Misc/Bell.png";
import EnterBlastedSteps from "./Enemy/Judge.png";
import GreatConchflies from "./Boss/GreatConchflies.png";
import GreatConchfliesTrans from "./Boss/GreatConchflies.png";
import NeedleStrike from "./Skill/NeedleStrike.png";
import NeedleStrikeTrans from "./Skill/NeedleStrike.png";
import EnterLastJudge from "./Boss/LastJudge.png";
import LastJudgeEncountered from "./Boss/LastJudge.png";
import LastJudge from "./Boss/LastJudge.png";
import EnterSinnersRoad from "./Enemy/Muckroach.png";
import Lugoli from "./Boss/Lugoli.png";
import EnterMist from "./Enemy/Wraith.png";
import MistCrossing from "./Enemy/Wraith.png";
import LeaveMist from "./Enemy/Wraith.png";
import EnterBilewater from "./Enemy/Stilkin.png";
import EnterExhaustOrgan from "./Boss/Phantom.png";
import Phantom from "./Boss/Phantom.png";
import PhantomTrans from "./Boss/Phantom.png";
import CrossStitch from "./Skill/CrossStitch.png";
import CrossStitchTrans from "./Skill/CrossStitch.png";
import TrailsEndTrans from "./NPC/Shakra.png";
import EnterTheSlab from "./Enemy/Wardenfly.png";
import WardenflyCaptureTrans from "./Enemy/Wardenfly.png";
import SlabKeyIndolent from "./Item/SlabKeyIndolent.png";
import SlabKeyHeretic from "./Item/SlabKeyHeretic.png";
import SlabKeyApostate from "./Item/SlabKeyApostate.png";
import Broodmother from "./Boss/Broodmother.png";
import EnterFirstSinner from "./Boss/FirstSinner.png";
import FirstSinnerEncountered from "./Boss/FirstSinner.png";
import FirstSinner from "./Boss/FirstSinner.png";
import RuneRage from "./Skill/RuneRage.png";
import RuneRageTrans from "./Skill/RuneRage.png";
import EnterMountFay from "./Enemy/Driftlin.png";
import EnterBrightvein from "./Enemy/Mnemonord.png";
import UpperMountFayTrans from "./Enemy/Mnemonid.png";
import FaydownCloak from "./Skill/FaydownCloak.png";
import EnterSandsOfKarak from "./Enemy/Crustcrawler.png";
import EnterVoltnest from "./Boss/Voltvyrm.png";
import Voltvyrm from "./Boss/Voltvyrm.png";
import RagingConchfly from "./Boss/GreatConchflies.png";
import RagingConchflyTrans from "./Boss/GreatConchflies.png";
import WatcherAtTheEdge from "./Boss/WatcherAtTheEdge.png";
import Act2Started from "./Event/Act2Started.png";
import EnterCogworkDancers from "./Boss/CogworkDancers.png";
import CogworkDancersEncountered from "./Boss/CogworkDancers.png";
import CogworkDancers from "./Boss/CogworkDancers.png";
import EnterCogworkCore from "./Enemy/CogworkChoirbug.png";
import SecondSentinelAwoken from "./Item/Cogheart.png";
import EnterWhisperingVaults from "./Enemy/Lampbearer.png";
import WhisperingVaultsArena from "./Enemy/Vaultkeeper.png";
import EnterGrandGate from "./Event/Act2Started.png";
import EnterChoralChambers from "./Enemy/ChoirFlyer.png";
import EnterSongclave from "./NPC/Caretaker.png";
import Trobbio from "./Boss/Trobbio.png";
import TrobbioTrans from "./Boss/Trobbio.png";
import MetMergwin from "./NPC/Mergwin.png";
import DeliveredCouriersRasher from "./Item/CouriersRasher.png";
import GreatTasteReward from "./Item/PaleOil.png";
import Clawline from "./Skill/Clawline.png";
import PostClawlineArenaTrans from "./Skill/Clawline.png";
import EnterHighHalls from "./Enemy/Minister.png";
import EnterHighHallsArena from "./Enemy/Maestro.png";
import HighHallsArena from "./Enemy/ChoirClapper.png";
import EnterSecondSentinel from "./Boss/SecondSentinel.png";
import SecondSentinelBossEncountered from "./Boss/SecondSentinel.png";
import SecondSentinel from "./Boss/SecondSentinel.png";
import EnterWhiteward from "./Enemy/Surgeon.png";
import PostWhitewardElevatorTrans from "./Enemy/Mortician.png";
import CollectedWhitewardKey from "./Item/CollectedWhitewardKey.png";
import CollectedSurgeonsKey from "./Item/CollectedSurgeonsKey.png";
import TheUnravelledEncountered from "./Boss/TheUnravelled.png";
import TheUnravelled from "./Boss/TheUnravelled.png";
import EnterMemorium from "./Enemy/Rhinogrund.png";
import EnterPutrifiedDucts from "./Enemy/Barnak.png";
import FleaFestivalBegin from "./Misc/FleaCaravan.png";
import FleaFestivalEnd from "./Item/PaleOil.png";
import Lace2 from "./Boss/Lace.png";
import PostLace2ArenaTrans from "./Boss/Lace.png";
import EnterTheCradle from "./Boss/Lace.png";
import PaleNails from "./Skill/PaleNails.png";
import PaleNailsTrans from "./Skill/PaleNails.png";
import VaultkeepersMelody from "./Melody/VaultkeepersMelody.png";
import VaultkeepersMelodyTrans from "./Melody/VaultkeepersMelody.png";
import ArchitectsMelody from "./Melody/ArchitectsMelody.png";
import ArchitectsMelodyTrans from "./Melody/ArchitectsMelody.png";
import ConductorsMelody from "./Melody/ConductorsMelody.png";
import ConductorsMelodyTrans from "./Melody/ConductorsMelody.png";
import UnlockedMelodyLift from "./Event/UnlockedMelodyLift.png";
import NeedleUpgrade1 from "./Item/Needle1.png";
import NeedleUpgrade2 from "./Item/Needle2.png";
import NeedleUpgrade3 from "./Item/Needle3.png";
import NeedleUpgrade4 from "./Item/Needle4.png";
import OnObtainMaskShard from "./Item/MaskShard.png";
import MaskShard1 from "./Item/MaskShard.png";
import MaskShard2 from "./Item/MaskShard.png";
import MaskShard3 from "./Item/MaskShard.png";
import Mask1 from "./Item/Mask.png";
import MaskShard5 from "./Item/MaskShard.png";
import MaskShard6 from "./Item/MaskShard.png";
import MaskShard7 from "./Item/MaskShard.png";
import Mask2 from "./Item/Mask.png";
import MaskShard9 from "./Item/MaskShard.png";
import MaskShard10 from "./Item/MaskShard.png";
import MaskShard11 from "./Item/MaskShard.png";
import Mask3 from "./Item/Mask.png";
import MaskShard13 from "./Item/MaskShard.png";
import MaskShard14 from "./Item/MaskShard.png";
import MaskShard15 from "./Item/MaskShard.png";
import Mask4 from "./Item/Mask.png";
import MaskShard17 from "./Item/MaskShard.png";
import MaskShard18 from "./Item/MaskShard.png";
import MaskShard19 from "./Item/MaskShard.png";
import Mask5 from "./Item/Mask.png";
import SpoolFragment1 from "./Item/SpoolFragment.png";
import Spool1 from "./Item/Spool.png";
import SpoolFragment3 from "./Item/SpoolFragment.png";
import Spool2 from "./Item/Spool.png";
import SpoolFragment5 from "./Item/SpoolFragment.png";
import Spool3 from "./Item/Spool.png";
import SpoolFragment7 from "./Item/SpoolFragment.png";
import Spool4 from "./Item/Spool.png";
import SpoolFragment9 from "./Item/SpoolFragment.png";
import Spool5 from "./Item/Spool.png";
import SpoolFragment11 from "./Item/SpoolFragment.png";
import Spool6 from "./Item/Spool.png";
import SpoolFragment13 from "./Item/SpoolFragment.png";
import Spool7 from "./Item/Spool.png";
import SpoolFragment15 from "./Item/SpoolFragment.png";
import Spool8 from "./Item/Spool.png";
import SpoolFragment17 from "./Item/SpoolFragment.png";
import Spool9 from "./Item/Spool.png";
import ToolPouch1 from "./Item/ToolPouch.png";
import ToolPouch2 from "./Item/ToolPouch.png";
import ToolPouch3 from "./Item/ToolPouch.png";
import ToolPouch4 from "./Item/ToolPouch.png";
import CraftingKit1 from "./Item/CraftingKit.png";
import CraftingKit2 from "./Item/CraftingKit.png";
import CraftingKit3 from "./Item/CraftingKit.png";
import CraftingKit4 from "./Item/CraftingKit.png";
import ReaperCrest from "./Crest/ReaperCrest.png";
import ReaperCrestTrans from "./Crest/ReaperCrest.png";
import WandererCrest from "./Crest/WandererCrest.png";
import WandererCrestTrans from "./Crest/WandererCrest.png";
import BeastCrest from "./Crest/BeastCrest.png";
import BeastCrestTrans from "./Crest/BeastCrest.png";
import ArchitectCrest from "./Crest/ArchitectCrest.png";
import ArchitectCrestTrans from "./Crest/ArchitectCrest.png";
import CurseCrest from "./Event/Cursed.png";
import GainedCurse from "./Event/Cursed.png";
import WitchCrest from "./Crest/WitchCrest.png";
import WitchCrestTrans from "./Crest/WitchCrest.png";
import ShamanCrest from "./Crest/ShamanCrest.png";
import ShamanCrestTrans from "./Crest/ShamanCrest.png";
import HunterCrestEvo1 from "./Crest/HunterCrestEvo1.png";
import VesticrestYellowSlot from "./Crest/VesticrestYellowSlot.png";
import VesticrestBlueSlot from "./Crest/VesticrestBlueSlot.png";
import HunterCrestEvo2 from "./Crest/HunterCrestEvo2.png";
import Sylphsong from "./Skill/Sylphsong.png";
import SylphsongTrans from "./Skill/Sylphsong.png";
import SavedFleaHuntersMarch from "./Misc/Flea.png";
import SavedFleaBellhart from "./Misc/Flea.png";
import SavedFleaMarrow from "./Misc/Flea.png";
import SavedFleaDeepDocksSprint from "./Misc/Flea.png";
import SavedFleaFarFieldsPilgrimsRest from "./Misc/Flea.png";
import SavedFleaFarFieldsTrap from "./Misc/Flea.png";
import SavedFleaSandsOfKarak from "./Misc/Flea.png";
import SavedFleaBlastedSteps from "./Misc/Flea.png";
import SavedFleaWormways from "./Misc/Flea.png";
import SavedFleaDeepDocksArena from "./Misc/Flea.png";
import SavedFleaDeepDocksBellway from "./Misc/Flea.png";
import SavedFleaBilewaterOrgan from "./Misc/Flea.png";
import SavedFleaSinnersRoad from "./Misc/Flea.png";
import SavedFleaGreymoorRoof from "./Misc/Flea.png";
import SavedFleaGreymoorLake from "./Misc/Flea.png";
import SavedFleaWhisperingVaults from "./Misc/Flea.png";
import SavedFleaSongclave from "./Misc/Flea.png";
import SavedFleaMountFay from "./Misc/Flea.png";
import SavedFleaBilewaterTrap from "./Misc/Flea.png";
import SavedFleaBilewaterThieves from "./Misc/Flea.png";
import SavedFleaShellwood from "./Misc/Flea.png";
import SavedFleaSlabBellway from "./Misc/Flea.png";
import SavedFleaSlabCage from "./Misc/Flea.png";
import SavedFleaChoralChambersWind from "./Misc/Flea.png";
import SavedFleaChoralChambersCage from "./Misc/Flea.png";
import SavedFleaUnderworksCauldron from "./Misc/Flea.png";
import SavedFleaUnderworksWispThicket from "./Misc/Flea.png";
import SavedFleaGiantFlea from "./Misc/GiantFlea.png";
import SavedFleaVog from "./Misc/Vog.png";
import SavedFleaKratt from "./Misc/Kratt.png";
import PutrifiedDuctsStation from "./Misc/Bellway.png";
import BellhartStation from "./Misc/Bellway.png";
import FarFieldsStation from "./Misc/Bellway.png";
import GrandBellwayStation from "./Misc/Bellway.png";
import BlastedStepsStation from "./Misc/Bellway.png";
import DeepDocksStation from "./Misc/Bellway.png";
import GreymoorStation from "./Misc/Bellway.png";
import SlabStation from "./Misc/Bellway.png";
import BilewaterStation from "./Misc/Bellway.png";
import ShellwoodStation from "./Misc/Bellway.png";
import BellwayTrans from "./Misc/Bellway.png";
import ChoralChambersTube from "./Misc/Ventrica.png";
import UnderworksTube from "./Misc/Ventrica.png";
import GrandBellwayTube from "./Misc/Ventrica.png";
import HighHallsTube from "./Misc/Ventrica.png";
import SongclaveTube from "./Misc/Ventrica.png";
import MemoriumTube from "./Misc/Ventrica.png";
import VentricaTrans from "./Misc/Ventrica.png";
import SeenShakraBonebottom from "./NPC/Shakra.png";
import SeenShakraMarrow from "./NPC/Shakra.png";
import SeenShakraDeepDocks from "./NPC/Shakra.png";
import SeenShakraFarFields from "./NPC/Shakra.png";
import SeenShakraWormways from "./NPC/Shakra.png";
import SeenShakraGreymoor from "./NPC/Shakra.png";
import SeenShakraBellhart from "./NPC/Shakra.png";
import SeenShakraShellwood from "./NPC/Shakra.png";
import SeenShakraHuntersMarch from "./NPC/Shakra.png";
import SeenShakraBlastedSteps from "./NPC/Shakra.png";
import SeenShakraSinnersRoad from "./NPC/Shakra.png";
import SeenShakraMountFay from "./NPC/Shakra.png";
import SeenShakraBilewater from "./NPC/Shakra.png";
import SeenShakraSandsOfKarak from "./NPC/Shakra.png";
import ShakraMapBuyout from "./NPC/Shakra.png";
import MetJubilanaEnclave from "./NPC/Jubilana.png";
import MetShermaEnclave from "./NPC/Sherma.png";
import UnlockedPrinceCage from "./NPC/GreenPrince.png";
import GreenPrinceInVerdania from "./NPC/GreenPrince.png";
import SeenFleatopiaEmpty from "./NPC/Mooshka.png";
import EnterBellEater from "./Boss/BellEater.png";
import BeastlingCall from "./Skill/BeastlingCall.png";
import SilkSoar from "./Skill/SilkSoar.png";
import ElegyOfTheDeep from "./Skill/ElegyOfTheDeep.png";
import EnterNylethMemory from "./Boss/Nyleth.png";
import NylethEncountered from "./Boss/Nyleth.png";
import Nyleth from "./Boss/Nyleth.png";
import HeartNyleth from "./Item/PollenHeart.png";
import EnterKhannMemory from "./Boss/CrustKingKhann.png";
import KhannEncountered from "./Boss/CrustKingKhann.png";
import CrustKingKhann from "./Boss/CrustKingKhann.png";
import HeartKhann from "./Item/EncrustedHeart.png";
import EnterKarmelitaMemory from "./Boss/SkarrsingerKarmelita.png";
import SkarrsingerKarmelita from "./Boss/SkarrsingerKarmelita.png";
import HeartKarmelita from "./Item/HuntersHeart.png";
import EnterVerdaniaMemory from "./Enemy/LeafGlider.png";
import EnterVerdaniaCastle from "./Boss/CloverDancers.png";
import Palestag from "./Boss/Palestag.png";
import CloverDancersEncountered from "./Boss/CloverDancers.png";
import CloverDancers from "./Boss/CloverDancers.png";
import HeartClover from "./Item/ConjoinedHeart.png";
import EnterRedMemory from "./NPC/ShamanSeeker.png";
import RedMemory from "./Item/Everbloom.png";
import BellhouseKeyConversation from "./Item/BellhomeKey.png";
import VerdaniaLakeFountainOrbs from "./Enemy/Nuphar.png";
import VerdaniaOrbsCollected from "./Enemy/Verdanir.png";
import Forebrothers from "./Boss/Forebrothers.png";
import Groal from "./Boss/Groal.png";
import SavageBeastfly1 from "./Boss/SavageBeastfly.png";
import SavageBeastfly2 from "./Boss/SavageBeastfly.png";
import CaravanTroupeGreymoor from "./NPC/Mooshka.png";
import CaravanTroupeBlastedSteps from "./NPC/Mooshka.png";
import CaravanTroupeFleatopia from "./NPC/Mooshka.png";
import SoldRelic from "./NPC/Scrounge.png";
import PavoTimePassed from "./NPC/Pavo.png";
import SongclaveBell from "./Misc/Bell.png";
import SkullTyrant1 from "./Boss/SkullTyrant.png";
import ShermaReturned from "./NPC/Sherma.png";
import JubilanaRescuedMemorium from "./NPC/Jubilana.png";
import JubilanaRescuedChoralChambers from "./NPC/Jubilana.png";
import SilkAndSoulOffered from "./Misc/Wayfarer.png";
import SoulSnareReady from "./Event/SilkAndSoul.png";
import EnterDestroyedCogworks from "./Misc/ShiningCog.png";
import DestroyedCogworksVoidArena from "./Enemy/Undercrank.png";
import EnterSeth from "./Boss/Seth.png";
import Seth from "./Boss/Seth.png";
import BallowMoved from "./NPC/Ballow.png";
import Act3Started from "./Event/Act3Started.png";
import DivingBellAbyssTrans from "./Item/DivingBellKey.png";
import EnterAbyss from "./Enemy/ShadowCreeper.png";
import AbyssEscape from "./Event/Act3Started.png";
import ReverseAbyssEscapeTrans from "./Event/Act3Started.png";
import LastDiveTrans from "./Event/LastDive.png";
import LostLaceEncountered from "./Boss/LostLace.png";
import AscendantsGrip from "./Tool/AscendantsGrip.png";
import BarbedBracelet from "./Tool/BarbedBracelet.png";
import ClawMirror from "./Tool/ClawMirror.png";
import ClawMirrors from "./Tool/ClawMirrors.png";
import Cogfly from "./Tool/Cogfly.png";
import CogworkWheel from "./Tool/CogworkWheel.png";
import Compass from "./Tool/Compass.png";
import Conchcutter from "./Tool/Conchcutter.png";
import Curveclaw from "./Tool/Curveclaw.png";
import Curvesickle from "./Tool/Curvesickle.png";
import DeadBugsPurse from "./Tool/DeadBugsPurse.png";
import DelversDrill from "./Tool/DelversDrill.png";
import DruidsEye from "./Tool/DruidsEye.png";
import DruidsEyes from "./Tool/DruidsEyes.png";
import EggofFlealia from "./Tool/EggofFlealia.png";
import FleaBrew from "./Tool/FleaBrew.png";
import Flintslate from "./Tool/Flintslate.png";
import FracturedMask from "./Tool/FracturedMask.png";
import InjectorBand from "./Tool/InjectorBand.png";
import Longclaw from "./Tool/Longclaw.png";
import Longpin from "./Tool/Longpin.png";
import MagmaBell from "./Tool/MagmaBell.png";
import MagnetiteBrooch from "./Tool/MagnetiteBrooch.png";
import MagnetiteDice from "./Tool/MagnetiteDice.png";
import MemoryCrystal from "./Tool/MemoryCrystal.png";
import Multibinder from "./Tool/Multibinder.png";
import NeedlePhial from "./Tool/NeedlePhial.png";
import Pimpillo from "./Tool/Pimpillo.png";
import PinBadge from "./Tool/PinBadge.png";
import PlasmiumPhial from "./Tool/PlasmiumPhial.png";
import PollipPouch from "./Tool/PollipPouch.png";
import QuickSling from "./Tool/QuickSling.png";
import ReserveBind from "./Tool/ReserveBind.png";
import RosaryCannon from "./Tool/RosaryCannon.png";
import SawtoothCirclet from "./Tool/SawtoothCirclet.png";
import Scuttlebrace from "./Tool/Scuttlebrace.png";
import ShardPendant from "./Tool/ShardPendant.png";
import ShellSatchel from "./Tool/ShellSatchel.png";
import SilkshotArchitect from "./Tool/SilkshotArchitect.png";
import SilkshotForge from "./Tool/SilkshotForge.png";
import SilkshotWeaver from "./Tool/SilkshotWeaver.png";
import SilkspeedAnklets from "./Tool/SilkspeedAnklets.png";
import SnareSetter from "./Tool/SnareSetter.png";
import SnitchPick from "./Tool/SnitchPick.png";
import SpiderStrings from "./Tool/SpiderStrings.png";
import SpoolExtender from "./Tool/SpoolExtender.png";
import StingShard from "./Tool/StingShard.png";
import StraightPin from "./Tool/StraightPin.png";
import Tacks from "./Tool/Tacks.png";
import ThiefsMark from "./Tool/ThiefsMark.png";
import ThreefoldPin from "./Tool/ThreefoldPin.png";
import ThrowingRing from "./Tool/ThrowingRing.png";
import VoltFilament from "./Tool/VoltFilament.png";
import Voltvessels from "./Tool/Voltvessels.png";
import WardingBell from "./Tool/WardingBell.png";
import Weavelight from "./Tool/Weavelight.png";
import WeightedBelt from "./Tool/WeightedBelt.png";
import WispfireLantern from "./Tool/WispfireLantern.png";
import WreathofPurity from "./Tool/WreathofPurity.png";
import LostLace from "./Boss/LostLace.png";
import MemoryLocket from "./Item/MemoryLocket.png";
import HunterCrest from "./Crest/HunterCrest.png";
export default {
  ManualSplit,
  StartNewGame,
  Act1Start,
  EndingSplit,
  EndingA,
  Menu,
  BenchAny,
  PlayerDeath,
  AnyTransition,
  TransitionExcludingDiscontinuities,
  MossMother,
  MossMotherTrans,
  EnterBoneBottom,
  EnterMosshome,
  SilkSpear,
  SilkSpearTrans,
  BoneBottomSimpleKey,
  EnterWeavenestAtla,
  BellBeast,
  BellBeastTrans,
  MarrowBell,
  SwiftStep,
  SwiftStepTrans,
  Lace1,
  Lace1Trans,
  DeepDocksBell,
  EnterWormways,
  EnterUpperWormways,
  Sharpdart,
  SharpdartTrans,
  EnterHuntersMarch,
  HuntersMarchPostMiddleArenaTransition,
  EnterFarFields,
  DriftersCloak,
  DriftersCloakTrans,
  FourthChorus,
  GurrTheOutcastEncountered,
  GurrTheOutcast,
  EnterGreymoor,
  GreymoorBell,
  Moorwing,
  MoorwingTrans,
  ThreadStorm,
  ThreadStormTrans,
  EnterHalfwayHomeBasement,
  YarnabySlap,
  Crawfather,
  EnterWispThicket,
  EnterFatherOfTheFlame,
  FatherOfTheFlame,
  EnterShellwood,
  ClingGrip,
  ClingGripTrans,
  ShellwoodBell,
  EnterBellhart,
  WidowEncountered,
  Widow,
  MenuNeedolinMemory,
  BellhartBell,
  EnterBlastedSteps,
  GreatConchflies,
  GreatConchfliesTrans,
  NeedleStrike,
  NeedleStrikeTrans,
  EnterLastJudge,
  LastJudgeEncountered,
  LastJudge,
  EnterSinnersRoad,
  Lugoli,
  EnterMist,
  MistCrossing,
  LeaveMist,
  EnterBilewater,
  EnterExhaustOrgan,
  Phantom,
  PhantomTrans,
  CrossStitch,
  CrossStitchTrans,
  TrailsEndTrans,
  EnterTheSlab,
  WardenflyCaptureTrans,
  SlabKeyIndolent,
  SlabKeyHeretic,
  SlabKeyApostate,
  Broodmother,
  EnterFirstSinner,
  FirstSinnerEncountered,
  FirstSinner,
  RuneRage,
  RuneRageTrans,
  EnterMountFay,
  EnterBrightvein,
  UpperMountFayTrans,
  FaydownCloak,
  EnterSandsOfKarak,
  EnterVoltnest,
  Voltvyrm,
  RagingConchfly,
  RagingConchflyTrans,
  WatcherAtTheEdge,
  Act2Started,
  EnterCogworkDancers,
  CogworkDancersEncountered,
  CogworkDancers,
  EnterCogworkCore,
  SecondSentinelAwoken,
  EnterWhisperingVaults,
  WhisperingVaultsArena,
  EnterGrandGate,
  EnterChoralChambers,
  EnterSongclave,
  Trobbio,
  TrobbioTrans,
  MetMergwin,
  DeliveredCouriersRasher,
  GreatTasteReward,
  Clawline,
  PostClawlineArenaTrans,
  EnterHighHalls,
  EnterHighHallsArena,
  HighHallsArena,
  EnterSecondSentinel,
  SecondSentinelBossEncountered,
  SecondSentinel,
  EnterWhiteward,
  PostWhitewardElevatorTrans,
  CollectedWhitewardKey,
  CollectedSurgeonsKey,
  TheUnravelledEncountered,
  TheUnravelled,
  EnterMemorium,
  EnterPutrifiedDucts,
  FleaFestivalBegin,
  FleaFestivalEnd,
  Lace2,
  PostLace2ArenaTrans,
  EnterTheCradle,
  PaleNails,
  PaleNailsTrans,
  VaultkeepersMelody,
  VaultkeepersMelodyTrans,
  ArchitectsMelody,
  ArchitectsMelodyTrans,
  ConductorsMelody,
  ConductorsMelodyTrans,
  UnlockedMelodyLift,
  NeedleUpgrade1,
  NeedleUpgrade2,
  NeedleUpgrade3,
  NeedleUpgrade4,
  OnObtainMaskShard,
  MaskShard1,
  MaskShard2,
  MaskShard3,
  Mask1,
  MaskShard5,
  MaskShard6,
  MaskShard7,
  Mask2,
  MaskShard9,
  MaskShard10,
  MaskShard11,
  Mask3,
  MaskShard13,
  MaskShard14,
  MaskShard15,
  Mask4,
  MaskShard17,
  MaskShard18,
  MaskShard19,
  Mask5,
  SpoolFragment1,
  Spool1,
  SpoolFragment3,
  Spool2,
  SpoolFragment5,
  Spool3,
  SpoolFragment7,
  Spool4,
  SpoolFragment9,
  Spool5,
  SpoolFragment11,
  Spool6,
  SpoolFragment13,
  Spool7,
  SpoolFragment15,
  Spool8,
  SpoolFragment17,
  Spool9,
  ToolPouch1,
  ToolPouch2,
  ToolPouch3,
  ToolPouch4,
  CraftingKit1,
  CraftingKit2,
  CraftingKit3,
  CraftingKit4,
  ReaperCrest,
  ReaperCrestTrans,
  WandererCrest,
  WandererCrestTrans,
  BeastCrest,
  BeastCrestTrans,
  ArchitectCrest,
  ArchitectCrestTrans,
  CurseCrest,
  GainedCurse,
  WitchCrest,
  WitchCrestTrans,
  ShamanCrest,
  ShamanCrestTrans,
  HunterCrestEvo1,
  VesticrestYellowSlot,
  VesticrestBlueSlot,
  HunterCrestEvo2,
  Sylphsong,
  SylphsongTrans,
  SavedFleaHuntersMarch,
  SavedFleaBellhart,
  SavedFleaMarrow,
  SavedFleaDeepDocksSprint,
  SavedFleaFarFieldsPilgrimsRest,
  SavedFleaFarFieldsTrap,
  SavedFleaSandsOfKarak,
  SavedFleaBlastedSteps,
  SavedFleaWormways,
  SavedFleaDeepDocksArena,
  SavedFleaDeepDocksBellway,
  SavedFleaBilewaterOrgan,
  SavedFleaSinnersRoad,
  SavedFleaGreymoorRoof,
  SavedFleaGreymoorLake,
  SavedFleaWhisperingVaults,
  SavedFleaSongclave,
  SavedFleaMountFay,
  SavedFleaBilewaterTrap,
  SavedFleaBilewaterThieves,
  SavedFleaShellwood,
  SavedFleaSlabBellway,
  SavedFleaSlabCage,
  SavedFleaChoralChambersWind,
  SavedFleaChoralChambersCage,
  SavedFleaUnderworksCauldron,
  SavedFleaUnderworksWispThicket,
  SavedFleaGiantFlea,
  SavedFleaVog,
  SavedFleaKratt,
  PutrifiedDuctsStation,
  BellhartStation,
  FarFieldsStation,
  GrandBellwayStation,
  BlastedStepsStation,
  DeepDocksStation,
  GreymoorStation,
  SlabStation,
  BilewaterStation,
  ShellwoodStation,
  BellwayTrans,
  ChoralChambersTube,
  UnderworksTube,
  GrandBellwayTube,
  HighHallsTube,
  SongclaveTube,
  MemoriumTube,
  VentricaTrans,
  SeenShakraBonebottom,
  SeenShakraMarrow,
  SeenShakraDeepDocks,
  SeenShakraFarFields,
  SeenShakraWormways,
  SeenShakraGreymoor,
  SeenShakraBellhart,
  SeenShakraShellwood,
  SeenShakraHuntersMarch,
  SeenShakraBlastedSteps,
  SeenShakraSinnersRoad,
  SeenShakraMountFay,
  SeenShakraBilewater,
  SeenShakraSandsOfKarak,
  ShakraMapBuyout,
  MetJubilanaEnclave,
  MetShermaEnclave,
  UnlockedPrinceCage,
  GreenPrinceInVerdania,
  SeenFleatopiaEmpty,
  EnterBellEater,
  BeastlingCall,
  SilkSoar,
  ElegyOfTheDeep,
  EnterNylethMemory,
  NylethEncountered,
  Nyleth,
  HeartNyleth,
  EnterKhannMemory,
  KhannEncountered,
  CrustKingKhann,
  HeartKhann,
  EnterKarmelitaMemory,
  SkarrsingerKarmelita,
  HeartKarmelita,
  EnterVerdaniaMemory,
  EnterVerdaniaCastle,
  Palestag,
  CloverDancersEncountered,
  CloverDancers,
  HeartClover,
  EnterRedMemory,
  RedMemory,
  BellhouseKeyConversation,
  VerdaniaLakeFountainOrbs,
  VerdaniaOrbsCollected,
  Forebrothers,
  Groal,
  SavageBeastfly1,
  SavageBeastfly2,
  CaravanTroupeGreymoor,
  CaravanTroupeBlastedSteps,
  CaravanTroupeFleatopia,
  SoldRelic,
  PavoTimePassed,
  SongclaveBell,
  SkullTyrant1,
  ShermaReturned,
  JubilanaRescuedMemorium,
  JubilanaRescuedChoralChambers,
  SilkAndSoulOffered,
  SoulSnareReady,
  EnterDestroyedCogworks,
  DestroyedCogworksVoidArena,
  EnterSeth,
  Seth,
  BallowMoved,
  Act3Started,
  DivingBellAbyssTrans,
  EnterAbyss,
  AbyssEscape,
  ReverseAbyssEscapeTrans,
  LastDiveTrans,
  LostLaceEncountered,
  AscendantsGrip,
  BarbedBracelet,
  ClawMirror,
  ClawMirrors,
  Cogfly,
  CogworkWheel,
  Compass,
  Conchcutter,
  Curveclaw,
  Curvesickle,
  DeadBugsPurse,
  DelversDrill,
  DruidsEye,
  DruidsEyes,
  EggofFlealia,
  FleaBrew,
  Flintslate,
  FracturedMask,
  InjectorBand,
  Longclaw,
  Longpin,
  MagmaBell,
  MagnetiteBrooch,
  MagnetiteDice,
  MemoryCrystal,
  Multibinder,
  NeedlePhial,
  Pimpillo,
  PinBadge,
  PlasmiumPhial,
  PollipPouch,
  QuickSling,
  ReserveBind,
  RosaryCannon,
  SawtoothCirclet,
  Scuttlebrace,
  ShardPendant,
  ShellSatchel,
  SilkshotArchitect,
  SilkshotForge,
  SilkshotWeaver,
  SilkspeedAnklets,
  SnareSetter,
  SnitchPick,
  SpiderStrings,
  SpoolExtender,
  StingShard,
  StraightPin,
  Tacks,
  ThiefsMark,
  ThreefoldPin,
  ThrowingRing,
  VoltFilament,
  Voltvessels,
  WardingBell,
  Weavelight,
  WeightedBelt,
  WispfireLantern,
  WreathofPurity,
  LostLace,
  MemoryLocket,
  HunterCrest,
};
