/* eslint-disable */
/* THIS FILE IS AUTOMATICALLY GENERATED */
import ManualSplit from "./Misc/Hornet.png";
import StartNewGame from "./Misc/Hornet.png";
import EndingSplit from "./Boss/GrandMotherSilk.png";
import EndingA from "./Boss/GrandMotherSilk.png";
import Menu from "./Item/Map.png";
import PlayerDeath from "./Misc/Hornet.png";
import AnyTransition from "./Misc/Hornet.png";
import MossMother from "./Boss/MossMother.png";
import MossMotherTrans from "./Boss/MossMother.png";
import SilkSpear from "./Skill/SilkSpear.png";
import SilkSpearTrans from "./Skill/SilkSpear.png";
import BellBeast from "./Boss/BellBeast.png";
import BellBeastTrans from "./Boss/BellBeast.png";
import MarrowBell from "./Misc/Bell.png";
import SwiftStep from "./Skill/SwiftStep.png";
import SwiftStepTrans from "./Skill/SwiftStep.png";
import Lace1 from "./Boss/Lace.png";
import Lace1Trans from "./Boss/Lace.png";
import DeepDocksBell from "./Misc/Bell.png";
import DriftersCloak from "./Skill/DriftersCloak.png";
import DriftersCloakTrans from "./Skill/DriftersCloak.png";
import FourthChorus from "./Boss/FourthChorus.png";
import EnterGreymoor from "./Enemy/Craw.png";
import GreymoorBell from "./Misc/Bell.png";
import Moorwing from "./Boss/Moorwing.png";
import MoorwingTrans from "./Boss/Moorwing.png";
import ClingGrip from "./Skill/ClingGrip.png";
import ClingGripTrans from "./Skill/ClingGrip.png";
import ShellwoodBell from "./Misc/Bell.png";
import Widow from "./Boss/Widow.png";
import BellhartBell from "./Misc/Bell.png";
import LastJudge from "./Boss/LastJudge.png";
import EnterMist from "./Enemy/Wraith.png";
import LeaveMist from "./Enemy/Wraith.png";
import Phantom from "./Boss/Phantom.png";
import Act2Started from "./Event/Act2Started.png";
import CogworkDancers from "./Boss/CogworkDancers.png";
import WhisperingVaultsGauntlet from "./Enemy/Vaultkeeper.png";
import Trobbio from "./Boss/Trobbio.png";
import TrobbioTrans from "./Boss/Trobbio.png";
import Clawline from "./Skill/Clawline.png";
import EnterHighHalls from "./Enemy/Minister.png";
import EnterHighHallsGauntlet from "./Enemy/Maestro.png";
import HighHallsGauntlet from "./Enemy/ChoirClapper.png";
import Lace2 from "./Boss/Lace.png";
import VaultkeepersMelody from "./Melody/VaultkeepersMelody.png";
import VaultkeepersMelodyTrans from "./Melody/VaultkeepersMelody.png";
import ArchitectsMelody from "./Melody/ArchitectsMelody.png";
import ArchitectsMelodyTrans from "./Melody/ArchitectsMelody.png";
import ConductorsMelody from "./Melody/ConductorsMelody.png";
import ConductorsMelodyTrans from "./Melody/ConductorsMelody.png";
import UnlockedMelodyLift from "./Event/UnlockedMelodyLift.png";
import NeedleUpgrade1 from "./Item/Needle1.png";
import NeedleUpgrade2 from "./Item/Needle2.png";
import NeedleUpgrade3 from "./Item/Needle3.png";
import NeedleUpgrade4 from "./Item/Needle4.png";
export default {
  ManualSplit,
  StartNewGame,
  EndingSplit,
  EndingA,
  Menu,
  PlayerDeath,
  AnyTransition,
  MossMother,
  MossMotherTrans,
  SilkSpear,
  SilkSpearTrans,
  BellBeast,
  BellBeastTrans,
  MarrowBell,
  SwiftStep,
  SwiftStepTrans,
  Lace1,
  Lace1Trans,
  DeepDocksBell,
  DriftersCloak,
  DriftersCloakTrans,
  FourthChorus,
  EnterGreymoor,
  GreymoorBell,
  Moorwing,
  MoorwingTrans,
  ClingGrip,
  ClingGripTrans,
  ShellwoodBell,
  Widow,
  BellhartBell,
  LastJudge,
  EnterMist,
  LeaveMist,
  Phantom,
  Act2Started,
  CogworkDancers,
  WhisperingVaultsGauntlet,
  Trobbio,
  TrobbioTrans,
  Clawline,
  EnterHighHalls,
  EnterHighHallsGauntlet,
  HighHallsGauntlet,
  Lace2,
  VaultkeepersMelody,
  VaultkeepersMelodyTrans,
  ArchitectsMelody,
  ArchitectsMelodyTrans,
  ConductorsMelody,
  ConductorsMelodyTrans,
  UnlockedMelodyLift,
  NeedleUpgrade1,
  NeedleUpgrade2,
  NeedleUpgrade3,
  NeedleUpgrade4,
};
