/* eslint-disable */
/* THIS FILE IS AUTOMATICALLY GENERATED */
import AbyssShriek from "./Skill/AbyssShriek.png";
import CrystalHeart from "./Skill/CrystalHeart.png";
import CycloneSlash from "./Skill/CycloneSlash.png";
import DashSlash from "./Skill/DashSlash.png";
import DescendingDark from "./Skill/DescendingDark.png";
import DesolateDive from "./Skill/DesolateDive.png";
import DreamNail from "./Skill/DreamNail.png";
import DreamNail2 from "./Skill/DreamNail2.png";
import DreamGate from "./Skill/DreamGate.png";
import GreatSlash from "./Skill/GreatSlash.png";
import HowlingWraiths from "./Skill/HowlingWraiths.png";
import IsmasTear from "./Skill/IsmasTear.png";
import MantisClaw from "./Skill/MantisClaw.png";
import MonarchWings from "./Skill/MonarchWings.png";
import MothwingCloak from "./Skill/MothwingCloak.png";
import ShadeCloak from "./Skill/ShadeCloak.png";
import ShadeSoul from "./Skill/ShadeSoul.png";
import VengefulSpirit from "./Skill/VengefulSpirit.png";
import CityKey from "./Item/CityKey.png";
import HasDelicateFlower from "./Item/DelicateFlower.png";
import ElegantKey from "./Item/ElegantKey.png";
import ElegantKeyShoptimised from "./Item/ElegantKey.png";
import GodTuner from "./Item/GodTuner.png";
import HuntersMark from "./Item/HuntersMark.png";
import KingsBrand from "./Item/KingsBrand.png";
import LoveKey from "./Item/LoveKey.png";
import LumaflyLantern from "./Item/LumaflyLantern.png";
import PaleLurkerKey from "./Item/SimpleKey.png";
import PaleOre from "./Item/PaleOre.png";
import SalubrasBlessing from "./Item/SalubrasBlessing.png";
import SimpleKey from "./Item/SimpleKey.png";
import SlyKey from "./Item/SlyKey.png";
import TramPass from "./Item/TramPass.png";
import MaskFragment1 from "./Fragment/MaskFragment1.png";
import MaskFragment2 from "./Fragment/MaskFragment2.png";
import MaskFragment3 from "./Fragment/MaskFragment3.png";
import Mask1 from "./Upgrade/Mask1.png";
import MaskFragment5 from "./Fragment/MaskFragment1.png";
import MaskFragment6 from "./Fragment/MaskFragment2.png";
import MaskFragment7 from "./Fragment/MaskFragment3.png";
import Mask2 from "./Upgrade/Mask1.png";
import MaskFragment9 from "./Fragment/MaskFragment1.png";
import MaskFragment10 from "./Fragment/MaskFragment2.png";
import MaskFragment11 from "./Fragment/MaskFragment3.png";
import Mask3 from "./Upgrade/Mask1.png";
import MaskFragment13 from "./Fragment/MaskFragment1.png";
import MaskFragment14 from "./Fragment/MaskFragment2.png";
import MaskFragment15 from "./Fragment/MaskFragment3.png";
import Mask4 from "./Upgrade/Mask1.png";
import NailUpgrade1 from "./Upgrade/NailUpgrade1.png";
import NailUpgrade2 from "./Upgrade/NailUpgrade2.png";
import NailUpgrade3 from "./Upgrade/NailUpgrade3.png";
import NailUpgrade4 from "./Upgrade/NailUpgrade4.png";
import VesselFragment1 from "./Fragment/VesselFragment1.png";
import VesselFragment2 from "./Fragment/VesselFragment1.png";
import Vessel1 from "./Upgrade/Vessel1.png";
import VesselFragment4 from "./Fragment/VesselFragment1.png";
import VesselFragment5 from "./Fragment/VesselFragment1.png";
import Vessel2 from "./Upgrade/Vessel1.png";
import VesselFragment7 from "./Fragment/VesselFragment1.png";
import VesselFragment8 from "./Fragment/VesselFragment1.png";
import Vessel3 from "./Upgrade/Vessel1.png";
import BrokenVessel from "./Boss/BrokenVessel.png";
import BroodingMawlek from "./Boss/BroodingMawlek.png";
import Collector from "./Boss/Collector.png";
import CrystalGuardian1 from "./Boss/CrystalGuardian1.png";
import CrystalGuardian2 from "./Boss/CrystalGuardian1.png";
import DungDefender from "./Boss/DungDefender.png";
import DungDefenderIdol from "./Relic/KingsIdol.png";
import ElderHu from "./Boss/ElderHu.png";
import ElderHuEssence from "./Boss/ElderHu.png";
import FalseKnight from "./Boss/FalseKnight.png";
import FailedKnight from "./Boss/FalseKnight.png";
import FailedChampionEssence from "./Boss/FalseKnight.png";
import Flukemarm from "./Boss/Flukemarm.png";
import Galien from "./Boss/Galien.png";
import GalienEssence from "./Boss/Galien.png";
import GodTamer from "./Boss/GodTamer.png";
import Gorb from "./Boss/Gorb.png";
import GorbEssence from "./Boss/Gorb.png";
import GreyPrince from "./Boss/GreyPrinceZote.png";
import GreyPrinceEssence from "./Boss/GreyPrinceZote.png";
import GruzMother from "./Boss/GruzMother.png";
import HiveKnight from "./Boss/HiveKnight.png";
import Hornet1 from "./Boss/Hornet1.png";
import Hornet2 from "./Boss/Hornet1.png";
import LostKin from "./Boss/BrokenVessel.png";
import LostKinEssence from "./Boss/BrokenVessel.png";
import MantisLords from "./Boss/MantisLords.png";
import Markoth from "./Boss/Markoth.png";
import MarkothEssence from "./Boss/Markoth.png";
import Marmu from "./Boss/Marmu.png";
import MarmuEssence from "./Boss/Marmu.png";
import MegaMossCharger from "./Boss/MassiveMossCharger.png";
import NightmareKingGrimm from "./Boss/NightmareKingGrimm.png";
import NoEyes from "./Boss/NoEyes.png";
import NoEyesEssence from "./Boss/NoEyes.png";
import Nosk from "./Boss/Nosk.png";
import KilledOblobbles from "./Boss/Oblobbles.png";
import MatoOroNailBros from "./Boss/MatoOroNailBros.png";
import PureVessel from "./Boss/PureVessel.png";
import RadianceBoss from "./Boss/RadianceBoss.png";
import HollowKnightBoss from "./Boss/HollowKnightBoss.png";
import SheoPaintmaster from "./Boss/SheoPaintmaster.png";
import SlyNailsage from "./Boss/SlyNailsage.png";
import SoulMaster from "./Boss/SoulMaster.png";
import SoulTyrant from "./Boss/SoulMaster.png";
import SoulTyrantEssence from "./Boss/SoulMaster.png";
import SoulTyrantEssenceWithSanctumGrub from "./Boss/SoulMaster.png";
import TraitorLord from "./Boss/TraitorLord.png";
import TroupeMasterGrimm from "./Boss/TroupeMasterGrimm.png";
import Uumuu from "./Boss/Uumuu.png";
import BlackKnight from "./Boss/WatcherKnights.png";
import WhiteDefender from "./Boss/WhiteDefender.png";
import WhiteDefenderEssence from "./Boss/WhiteDefender.png";
import Xero from "./Boss/Xero.png";
import XeroEssence from "./Boss/Xero.png";
import VengeflyKingP from "./Boss/VengeflyKing.png";
import GruzMotherP from "./Boss/GruzMother.png";
import FalseKnightP from "./Boss/FalseKnight.png";
import MassiveMossChargerP from "./Boss/MassiveMossCharger.png";
import Hornet1P from "./Boss/Hornet1.png";
import GorbP from "./Boss/Gorb.png";
import DungDefenderP from "./Boss/DungDefender.png";
import SoulWarriorP from "./Boss/SoulWarrior.png";
import BroodingMawlekP from "./Boss/BroodingMawlek.png";
import OroMatoNailBrosP from "./Boss/MatoOroNailBros.png";
import XeroP from "./Boss/Xero.png";
import CrystalGuardianP from "./Boss/CrystalGuardian1.png";
import SoulMasterP from "./Boss/SoulMaster.png";
import OblobblesP from "./Boss/Oblobbles.png";
import MantisLordsP from "./Boss/MantisLords.png";
import MarmuP from "./Boss/Marmu.png";
import NoskP from "./Boss/Nosk.png";
import FlukemarmP from "./Boss/Flukemarm.png";
import BrokenVesselP from "./Boss/BrokenVessel.png";
import SheoPaintmasterP from "./Boss/SheoPaintmaster.png";
import HiveKnightP from "./Boss/HiveKnight.png";
import ElderHuP from "./Boss/ElderHu.png";
import CollectorP from "./Boss/Collector.png";
import GodTamerP from "./Boss/GodTamer.png";
import TroupeMasterGrimmP from "./Boss/TroupeMasterGrimm.png";
import GalienP from "./Boss/Galien.png";
import GreyPrinceZoteP from "./Boss/GreyPrinceZote.png";
import UumuuP from "./Boss/Uumuu.png";
import Hornet2P from "./Boss/Hornet1.png";
import SlyP from "./Boss/SlyNailsage.png";
import EnragedGuardianP from "./Boss/CrystalGuardian1.png";
import LostKinP from "./Boss/BrokenVessel.png";
import NoEyesP from "./Boss/NoEyes.png";
import TraitorLordP from "./Boss/TraitorLord.png";
import WhiteDefenderP from "./Boss/WhiteDefender.png";
import FailedChampionP from "./Boss/FalseKnight.png";
import MarkothP from "./Boss/Markoth.png";
import WatcherKnightsP from "./Boss/WatcherKnights.png";
import SoulTyrantP from "./Boss/SoulMaster.png";
import PureVesselP from "./Boss/PureVessel.png";
import NoskHornetP from "./Boss/NoskHornet.png";
import NightmareKingGrimmP from "./Boss/NightmareKingGrimm.png";
import Hegemol from "./Dreamer/Herrah.png";
import Lurien from "./Dreamer/Lurien.png";
import Monomon from "./Dreamer/Monomon.png";
import Dreamer1 from "./Dreamer/Dreamer.png";
import Dreamer2 from "./Dreamer/Dreamer.png";
import Dreamer3 from "./Dreamer/Dreamer.png";
import PreGrimmShop from "./Boss/TroupeMasterGrimm.png";
import SlyShopFinished from "./Misc/Sly.png";
import CanOvercharm from "./Achievement/Charmed.png";
import UnchainedHollowKnight from "./Boss/HollowKnightBoss.png";
import WatcherChandelier from "./Misc/WatcherChandelier.png";
import CityGateOpen from "./Item/CityKey.png";
import PlayerDeath from "./Enemy/Shade.png";
import EndingSplit from "./Misc/Knight.png";
import FlowerQuest from "./Item/DelicateFlower.png";
import FlowerRewardGiven from "./Achievement/Solace.png";
import HappyCouplePlayerDataEvent from "./Achievement/HappyCouple.png";
import NailsmithKilled from "./Achievement/Purity.png";
import NightmareLantern from "./Misc/Flame.png";
import NightmareLanternDestroyed from "./Achievement/Banishment.png";
import HollowKnightDreamnail from "./Boss/HollowKnightBoss.png";
import SeerDeparts from "./Achievement/Ascension.png";
import SpiritGladeOpen from "./Achievement/Attunement.png";
import BeastsDenTrapBench from "./Misc/Bench.png";
import EternalOrdealUnlocked from "./Enemy/Zote.png";
import EternalOrdealAchieved from "./Enemy/Zote.png";
import ColosseumBronzeUnlocked from "./Achievement/Warrior.png";
import ColosseumSilverUnlocked from "./Achievement/Conqueror.png";
import ColosseumGoldUnlocked from "./Achievement/Fool.png";
import ColosseumBronze from "./Achievement/Warrior.png";
import ColosseumSilver from "./Achievement/Conqueror.png";
import ColosseumGold from "./Achievement/Fool.png";
import ColosseumBronzeExit from "./Achievement/Warrior.png";
import ColosseumSilverExit from "./Achievement/Conqueror.png";
import ColosseumGoldExit from "./Achievement/Fool.png";
import Pantheon1 from "./Achievement/Brotherhood.png";
import Pantheon2 from "./Achievement/Inspiration.png";
import Pantheon3 from "./Achievement/Focus.png";
import Pantheon4 from "./Achievement/SoulAndShade.png";
import Pantheon5 from "./Achievement/EmbraceTheVoid.png";
import PathOfPain from "./Item/SealOfBinding.png";
import AspidHunter from "./Enemy/AspidHunter.png";
import Aluba from "./Enemy/Aluba.png";
import HuskMiner from "./Enemy/HuskMiner.png";
import GreatHopper from "./Enemy/GreatHopper.png";
import GorgeousHusk from "./Enemy/GorgeousHusk.png";
import MenderBug from "./Enemy/MenderBug.png";
import killedSanctumWarrior from "./Boss/SoulWarrior.png";
import killedSoulTwister from "./Enemy/SoulTwister.png";
import MossKnight from "./Enemy/MossKnight.png";
import MushroomBrawler from "./Enemy/ShrumalOgre.png";
import Zote1 from "./Boss/VengeflyKing.png";
import Zote2 from "./Enemy/Zote.png";
import ZoteKilled from "./Enemy/Zote.png";
import CrossroadsStation from "./Misc/Stag.png";
import GreenpathStation from "./Misc/Stag.png";
import QueensStationStation from "./Misc/Stag.png";
import QueensGardensStation from "./Misc/Stag.png";
import StoreroomsStation from "./Misc/Stag.png";
import KingsStationStation from "./Misc/Stag.png";
import RestingGroundsStation from "./Misc/Stag.png";
import DeepnestStation from "./Misc/Stag.png";
import HiddenStationStation from "./Misc/Stag.png";
import StagnestStation from "./Misc/Stag.png";
import MrMushroom1 from "./NPC/MrMushroom.png";
import MrMushroom2 from "./NPC/MrMushroom.png";
import MrMushroom3 from "./NPC/MrMushroom.png";
import MrMushroom4 from "./NPC/MrMushroom.png";
import MrMushroom5 from "./NPC/MrMushroom.png";
import MrMushroom6 from "./NPC/MrMushroom.png";
import MrMushroom7 from "./NPC/MrMushroom.png";
import Abyss from "./Enemy/ShadowCreeper.png";
import CityOfTears from "./Enemy/HuskSentry.png";
import Colosseum from "./Misc/Colosseum.png";
import CrystalPeak from "./Enemy/CrystalCrawler.png";
import Deepnest from "./Enemy/Dirtcarver.png";
import DeepnestSpa from "./Misc/HotSpring.png";
import Dirtmouth from "./NPC/Elderbug.png";
import FogCanyon from "./Enemy/Uoma.png";
import ForgottenCrossroads from "./Enemy/Tiktik.png";
import FungalWastes from "./Enemy/Ambloom.png";
import Godhome from "./Misc/Godseeker.png";
import Greenpath from "./Enemy/Mosscreep.png";
import Hive from "./Enemy/Hiveling.png";
import InfectedCrossroads from "./Enemy/FuriousVengefly.png";
import KingdomsEdge from "./Enemy/PrimalAspid.png";
import QueensGardens from "./Enemy/SpinyHusk.png";
import RestingGrounds from "./Misc/Seer.png";
import RoyalWaterways from "./Enemy/Flukefey.png";
import TeachersArchive from "./Enemy/ChargedLumafly.png";
import WhitePalace from "./Enemy/Wingmould.png";
import WhitePalaceSecretRoom from "./Enemy/Kingsmould.png";
import BasinEntry from "./Enemy/ShadowCreeper.png";
import BlueLake from "./Achievement/Witness.png";
import CrystalPeakEntry from "./Enemy/CrystalCrawler.png";
import EnterAnyDream from "./Skill/DreamNail.png";
import FogCanyonEntry from "./Enemy/Uoma.png";
import TransGorgeousHusk from "./Enemy/GorgeousHusk.png";
import EnterGreenpath from "./Enemy/Mosscreep.png";
import EnterGreenpathWithOvercharm from "./Enemy/Mosscreep.png";
import TransClaw from "./Skill/MantisClaw.png";
import TransDescendingDark from "./Skill/DescendingDark.png";
import HiveEntry from "./Enemy/Hiveling.png";
import KingsPass from "./Enemy/Vengefly.png";
import KingsPassEnterFromTown from "./Enemy/Vengefly.png";
import KingdomsEdgeEntry from "./Enemy/PrimalAspid.png";
import KingdomsEdgeOvercharmedEntry from "./Enemy/PrimalAspid.png";
import EnterNKG from "./Enemy/GrimmkinNightmare.png";
import QueensGardensEntry from "./Enemy/SpinyHusk.png";
import QueensGardensFrogsTrans from "./Enemy/SpinyHusk.png";
import QueensGardensPostArenaTransition from "./Enemy/SpinyHusk.png";
import EnterSanctum from "./Enemy/Folly.png";
import EnterSanctumWithShadeSoul from "./Enemy/Folly.png";
import WaterwaysEntry from "./Enemy/Flukefey.png";
import WhitePalaceEntry from "./Enemy/Wingmould.png";
import BaldurShell from "./Charm/BaldurShell.png";
import Dashmaster from "./Charm/Dashmaster.png";
import DeepFocus from "./Charm/DeepFocus.png";
import DefendersCrest from "./Charm/DefendersCrest.png";
import Dreamshield from "./Charm/Dreamshield.png";
import DreamWielder from "./Charm/DreamWielder.png";
import Flukenest from "./Charm/Flukenest.png";
import FragileGreed from "./Charm/FragileGreed.png";
import FragileHeart from "./Charm/FragileHeart.png";
import FragileStrength from "./Charm/FragileStrength.png";
import FuryOfTheFallen from "./Charm/FuryOfTheFallen.png";
import GatheringSwarm from "./Charm/GatheringSwarm.png";
import GlowingWomb from "./Charm/GlowingWomb.png";
import Grimmchild from "./Charm/Grimmchild.png";
import Grimmchild2 from "./Charm/Grimmchild2.png";
import Grimmchild3 from "./Charm/Grimmchild3.png";
import Grimmchild4 from "./Charm/Grimmchild4.png";
import GrubberflysElegy from "./Charm/GrubberflysElegy.png";
import Grubsong from "./Charm/Grubsong.png";
import HeavyBlow from "./Charm/HeavyBlow.png";
import Hiveblood from "./Charm/Hiveblood.png";
import JonisBlessing from "./Charm/JonisBlessing.png";
import WhiteFragmentLeft from "./Charm/WhiteFragmentLeft.png";
import WhiteFragmentRight from "./Charm/WhiteFragmentRight.png";
import Kingsoul from "./Charm/Kingsoul.png";
import LifebloodCore from "./Charm/LifebloodCore.png";
import LifebloodHeart from "./Charm/LifebloodHeart.png";
import Longnail from "./Charm/Longnail.png";
import MarkOfPride from "./Charm/MarkOfPride.png";
import NailmastersGlory from "./Charm/NailmastersGlory.png";
import QuickFocus from "./Charm/QuickFocus.png";
import QuickSlash from "./Charm/QuickSlash.png";
import ShamanStone from "./Charm/ShamanStone.png";
import ShapeOfUnn from "./Charm/ShapeOfUnn.png";
import SharpShadow from "./Charm/SharpShadow.png";
import SoulCatcher from "./Charm/SoulCatcher.png";
import SoulEater from "./Charm/SoulEater.png";
import SpellTwister from "./Charm/SpellTwister.png";
import SporeShroom from "./Charm/SporeShroom.png";
import Sprintmaster from "./Charm/Sprintmaster.png";
import StalwartShell from "./Charm/StalwartShell.png";
import SteadyBody from "./Charm/SteadyBody.png";
import ThornsOfAgony from "./Charm/ThornsOfAgony.png";
import UnbreakableGreed from "./Charm/UnbreakableGreed.png";
import UnbreakableHeart from "./Charm/UnbreakableHeart.png";
import UnbreakableStrength from "./Charm/UnbreakableStrength.png";
import VoidHeart from "./Charm/VoidHeart.png";
import WaywardCompass from "./Charm/WaywardCompass.png";
import Weaversong from "./Charm/Weaversong.png";
import NotchShrumalOgres from "./Item/CharmNotch.png";
import NotchFogCanyon from "./Item/CharmNotch.png";
import NotchGrimm from "./Item/CharmNotch.png";
import NotchSalubra1 from "./Item/CharmNotch.png";
import NotchSalubra2 from "./Item/CharmNotch.png";
import NotchSalubra3 from "./Item/CharmNotch.png";
import NotchSalubra4 from "./Item/CharmNotch.png";
import Lemm2 from "./Misc/Lemm.png";
import AllCharmNotchesLemm2CP from "./Misc/Lemm.png";
import MetGreyMourner from "./NPC/GreyMourner.png";
import GreyMournerSeerAscended from "./NPC/GreyMourner.png";
import ElderbugFlower from "./NPC/ElderbugFlower.png";
import givenGodseekerFlower from "./Item/DelicateFlower.png";
import givenOroFlower from "./Item/DelicateFlower.png";
import givenWhiteLadyFlower from "./Item/DelicateFlower.png";
import givenEmilitiaFlower from "./Item/DelicateFlower.png";
import BrettaRescued from "./NPC/BrettaRescued.png";
import BrummFlame from "./Misc/FlameConsumed.png";
import LittleFool from "./NPC/LittleFool.png";
import SlyRescued from "./NPC/SlyRescued.png";
import Flame1 from "./Misc/FlameConsumed.png";
import Flame2 from "./Misc/FlameConsumed.png";
import Flame3 from "./Misc/FlameConsumed.png";
import Ore1 from "./Item/PaleOre.png";
import Ore2 from "./Item/PaleOre.png";
import Ore3 from "./Item/PaleOre.png";
import Ore4 from "./Item/PaleOre.png";
import Ore5 from "./Item/PaleOre.png";
import Ore6 from "./Item/PaleOre.png";
import Grub1 from "./NPC/Grub.png";
import Grub2 from "./NPC/Grub.png";
import Grub3 from "./NPC/Grub.png";
import Grub4 from "./NPC/Grub.png";
import Grub5 from "./NPC/Grub.png";
import Grub6 from "./NPC/Grub.png";
import Grub7 from "./NPC/Grub.png";
import Grub8 from "./NPC/Grub.png";
import Grub9 from "./NPC/Grub.png";
import Grub10 from "./NPC/Grub.png";
import Grub11 from "./NPC/Grub.png";
import Grub12 from "./NPC/Grub.png";
import Grub13 from "./NPC/Grub.png";
import Grub14 from "./NPC/Grub.png";
import Grub15 from "./NPC/Grub.png";
import Grub16 from "./NPC/Grub.png";
import Grub17 from "./NPC/Grub.png";
import Grub18 from "./NPC/Grub.png";
import Grub19 from "./NPC/Grub.png";
import Grub20 from "./NPC/Grub.png";
import Grub21 from "./NPC/Grub.png";
import Grub22 from "./NPC/Grub.png";
import Grub23 from "./NPC/Grub.png";
import Grub24 from "./NPC/Grub.png";
import Grub25 from "./NPC/Grub.png";
import Grub26 from "./NPC/Grub.png";
import Grub27 from "./NPC/Grub.png";
import Grub28 from "./NPC/Grub.png";
import Grub29 from "./NPC/Grub.png";
import Grub30 from "./NPC/Grub.png";
import Grub31 from "./NPC/Grub.png";
import Grub32 from "./NPC/Grub.png";
import Grub33 from "./NPC/Grub.png";
import Grub34 from "./NPC/Grub.png";
import Grub35 from "./NPC/Grub.png";
import Grub36 from "./NPC/Grub.png";
import Grub37 from "./NPC/Grub.png";
import Grub38 from "./NPC/Grub.png";
import Grub39 from "./NPC/Grub.png";
import Grub40 from "./NPC/Grub.png";
import Grub41 from "./NPC/Grub.png";
import Grub42 from "./NPC/Grub.png";
import Grub43 from "./NPC/Grub.png";
import Grub44 from "./NPC/Grub.png";
import Grub45 from "./NPC/Grub.png";
import Grub46 from "./NPC/Grub.png";
import GrubBasinDive from "./NPC/Grub.png";
import GrubBasinWings from "./NPC/Grub.png";
import GrubCityBelowLoveTower from "./NPC/Grub.png";
import GrubCityBelowSanctum from "./NPC/Grub.png";
import GrubCityCollectorAll from "./NPC/Grub.png";
import GrubCityGuardHouse from "./NPC/Grub.png";
import GrubCitySanctum from "./NPC/Grub.png";
import GrubCitySpire from "./NPC/Grub.png";
import GrubCliffsBaldurShell from "./NPC/Grub.png";
import GrubCrossroadsAcid from "./NPC/Grub.png";
import GrubCrossroadsGuarded from "./NPC/Grub.png";
import GrubCrossroadsSpikes from "./NPC/Grub.png";
import GrubCrossroadsVengefly from "./NPC/Grub.png";
import GrubCrossroadsWall from "./NPC/Grub.png";
import GrubCrystalPeaksBottomLever from "./NPC/Grub.png";
import GrubCrystalPeaksCrown from "./NPC/Grub.png";
import GrubCrystalPeaksCrushers from "./NPC/Grub.png";
import GrubCrystalPeaksCrystalHeart from "./NPC/Grub.png";
import GrubCrystalPeaksMimics from "./NPC/Grub.png";
import GrubCrystalPeaksMound from "./NPC/Grub.png";
import GrubCrystalPeaksSpikes from "./NPC/Grub.png";
import GrubDeepnestBeastsDen from "./NPC/Grub.png";
import GrubDeepnestDark from "./NPC/Grub.png";
import GrubDeepnestMimics from "./NPC/Grub.png";
import GrubDeepnestNosk from "./NPC/Grub.png";
import GrubDeepnestSpikes from "./NPC/Grub.png";
import GrubFogCanyonArchives from "./NPC/Grub.png";
import GrubFungalBouncy from "./NPC/Grub.png";
import GrubFungalSporeShroom from "./NPC/Grub.png";
import GrubGreenpathCornifer from "./NPC/Grub.png";
import GrubGreenpathHunter from "./NPC/Grub.png";
import GrubGreenpathMossKnight from "./NPC/Grub.png";
import GrubGreenpathVesselFragment from "./NPC/Grub.png";
import GrubHiveExternal from "./NPC/Grub.png";
import GrubHiveInternal from "./NPC/Grub.png";
import GrubKingdomsEdgeCenter from "./NPC/Grub.png";
import GrubKingdomsEdgeOro from "./NPC/Grub.png";
import GrubQueensGardensBelowStag from "./NPC/Grub.png";
import GrubQueensGardensUpper from "./NPC/Grub.png";
import GrubQueensGardensWhiteLady from "./NPC/Grub.png";
import GrubRestingGroundsCrypts from "./NPC/Grub.png";
import GrubWaterwaysCenter from "./NPC/Grub.png";
import GrubWaterwaysHwurmps from "./NPC/Grub.png";
import GrubWaterwaysIsma from "./NPC/Grub.png";
import TreeMound from "./Misc/WhisperingRoot.png";
import TreeCity from "./Misc/WhisperingRoot.png";
import TreePeak from "./Misc/WhisperingRoot.png";
import TreeDeepnest from "./Misc/WhisperingRoot.png";
import TreeCrossroads from "./Misc/WhisperingRoot.png";
import TreeLegEater from "./Misc/WhisperingRoot.png";
import TreeMantisVillage from "./Misc/WhisperingRoot.png";
import TreeGreenpath from "./Misc/WhisperingRoot.png";
import TreeHive from "./Misc/WhisperingRoot.png";
import TreeCliffs from "./Misc/WhisperingRoot.png";
import TreeKingdomsEdge from "./Misc/WhisperingRoot.png";
import TreeQueensGardens from "./Misc/WhisperingRoot.png";
import TreeRestingGrounds from "./Misc/WhisperingRoot.png";
import TreeWaterways from "./Misc/WhisperingRoot.png";
import TreeGlade from "./Misc/WhisperingRoot.png";
import TollBenchQG from "./Misc/Bench.png";
import TollBenchCity from "./Misc/Bench.png";
import TollBenchBasin from "./Misc/Bench.png";
import WaterwaysManhole from "./Misc/Bench.png";
import TramDeepnest from "./Misc/Tram.png";
import WhitePalaceOrb1 from "./Enemy/Wingmould.png";
import WhitePalaceOrb3 from "./Enemy/Wingmould.png";
import WhitePalaceOrb2 from "./Enemy/Wingmould.png";
import WhitePalaceLowerEntry from "./Enemy/Wingmould.png";
import WhitePalaceLowerOrb from "./Enemy/Wingmould.png";
import WhitePalaceLeftEntry from "./Enemy/Wingmould.png";
import WhitePalaceLeftWingMid from "./Enemy/Wingmould.png";
import WhitePalaceRightEntry from "./Enemy/Wingmould.png";
import WhitePalaceRightClimb from "./Enemy/Wingmould.png";
import WhitePalaceRightSqueeze from "./Enemy/Wingmould.png";
import WhitePalaceRightDone from "./Enemy/Wingmould.png";
import WhitePalaceTopEntry from "./Enemy/Wingmould.png";
import WhitePalaceTopClimb from "./Enemy/Wingmould.png";
import WhitePalaceTopLeverRoom from "./Enemy/Wingmould.png";
import WhitePalaceTopLastPlats from "./Enemy/Wingmould.png";
import WhitePalaceThroneRoom from "./Enemy/Wingmould.png";
import WhitePalaceAtrium from "./Enemy/Wingmould.png";
import PathOfPainEntry from "./Enemy/Wingmould.png";
import PathOfPainTransition1 from "./Enemy/Wingmould.png";
import PathOfPainTransition2 from "./Enemy/Wingmould.png";
import PathOfPainTransition3 from "./Enemy/Wingmould.png";
import DgateKingdomsEdgeAcid from "./Skill/DreamGate.png";
import SoulMasterEncountered from "./Boss/SoulMaster.png";
import GodhomeBench from "./Misc/Godseeker.png";
import GodhomeLoreRoom from "./Misc/Godseeker.png";
import Pantheon1to4Entry from "./Misc/Godseeker.png";
import Pantheon5Entry from "./Misc/Godseeker.png";
import Menu from "./Misc/MapQuill.png";
import MenuClaw from "./Skill/MantisClaw.png";
import MenuGorgeousHusk from "./Enemy/GorgeousHusk.png";
import CorniferAtHome from "./Misc/Iselda.png";
import AllSeals from "./Relic/HallownestSeal.png";
import AllEggs from "./Item/RancidEgg.png";
import SlySimpleKey from "./Item/SimpleKey.png";
import AllBreakables from "./Charm/FragileStrengthBroken.png";
import AllUnbreakables from "./Charm/UnbreakableStrength.png";
import MetEmilitia from "./NPC/Emilitia.png";
import mapDirtmouth from "./Misc/Map.png";
import mapCrossroads from "./Misc/Map.png";
import mapGreenpath from "./Misc/Map.png";
import mapFogCanyon from "./Misc/Map.png";
import mapRoyalGardens from "./Misc/Map.png";
import mapFungalWastes from "./Misc/Map.png";
import mapCity from "./Misc/Map.png";
import mapWaterways from "./Misc/Map.png";
import mapMines from "./Misc/Map.png";
import mapDeepnest from "./Misc/Map.png";
import mapCliffs from "./Misc/Map.png";
import mapOutskirts from "./Misc/Map.png";
import mapRestingGrounds from "./Misc/Map.png";
import mapAbyss from "./Misc/Map.png";
import OnObtainGhostMarissa from "./NPC/Marissa.png";
import OnObtainGhostCaelifFera from "./NPC/CaelifFera.png";
import OnObtainGhostPoggy from "./NPC/Poggy.png";
import OnObtainGhostGravedigger from "./NPC/Gravedigger.png";
import OnObtainGhostJoni from "./NPC/Joni.png";
import OnObtainGhostCloth from "./NPC/Cloth.png";
import OnObtainGhostVespa from "./NPC/Vespa.png";
import OnObtainGhostRevek from "./NPC/Revek.png";
import OnObtainWanderersJournal from "./Relic/WanderersJournal.png";
import OnObtainHallownestSeal from "./Relic/HallownestSeal.png";
import OnObtainKingsIdol from "./Relic/KingsIdol.png";
import OnObtainArcaneEgg from "./Relic/ArcaneEgg.png";
import OnObtainRancidEgg from "./Item/RancidEgg.png";
import OnObtainMaskShard from "./Fragment/MaskShard.png";
import OnObtainVesselFragment from "./Fragment/VesselFragment1.png";
import OnObtainSimpleKey from "./Item/SimpleKey.png";
import OnUseSimpleKey from "./Item/SimpleKey.png";
import OnObtainGrub from "./NPC/Grub.png";
import AnyTransition from "./Misc/Knight.png";
import TransitionAfterSaveState from "./Misc/Knight.png";
import ManualSplit from "./Misc/Knight.png";
export default {
    AbyssShriek,
    CrystalHeart,
    CycloneSlash,
    DashSlash,
    DescendingDark,
    DesolateDive,
    DreamNail,
    DreamNail2,
    DreamGate,
    GreatSlash,
    HowlingWraiths,
    IsmasTear,
    MantisClaw,
    MonarchWings,
    MothwingCloak,
    ShadeCloak,
    ShadeSoul,
    VengefulSpirit,
    CityKey,
    HasDelicateFlower,
    ElegantKey,
    ElegantKeyShoptimised,
    GodTuner,
    HuntersMark,
    KingsBrand,
    LoveKey,
    LumaflyLantern,
    PaleLurkerKey,
    PaleOre,
    SalubrasBlessing,
    SimpleKey,
    SlyKey,
    TramPass,
    MaskFragment1,
    MaskFragment2,
    MaskFragment3,
    Mask1,
    MaskFragment5,
    MaskFragment6,
    MaskFragment7,
    Mask2,
    MaskFragment9,
    MaskFragment10,
    MaskFragment11,
    Mask3,
    MaskFragment13,
    MaskFragment14,
    MaskFragment15,
    Mask4,
    NailUpgrade1,
    NailUpgrade2,
    NailUpgrade3,
    NailUpgrade4,
    VesselFragment1,
    VesselFragment2,
    Vessel1,
    VesselFragment4,
    VesselFragment5,
    Vessel2,
    VesselFragment7,
    VesselFragment8,
    Vessel3,
    BrokenVessel,
    BroodingMawlek,
    Collector,
    CrystalGuardian1,
    CrystalGuardian2,
    DungDefender,
    DungDefenderIdol,
    ElderHu,
    ElderHuEssence,
    FalseKnight,
    FailedKnight,
    FailedChampionEssence,
    Flukemarm,
    Galien,
    GalienEssence,
    GodTamer,
    Gorb,
    GorbEssence,
    GreyPrince,
    GreyPrinceEssence,
    GruzMother,
    HiveKnight,
    Hornet1,
    Hornet2,
    LostKin,
    LostKinEssence,
    MantisLords,
    Markoth,
    MarkothEssence,
    Marmu,
    MarmuEssence,
    MegaMossCharger,
    NightmareKingGrimm,
    NoEyes,
    NoEyesEssence,
    Nosk,
    KilledOblobbles,
    MatoOroNailBros,
    PureVessel,
    RadianceBoss,
    HollowKnightBoss,
    SheoPaintmaster,
    SlyNailsage,
    SoulMaster,
    SoulTyrant,
    SoulTyrantEssence,
    SoulTyrantEssenceWithSanctumGrub,
    TraitorLord,
    TroupeMasterGrimm,
    Uumuu,
    BlackKnight,
    WhiteDefender,
    WhiteDefenderEssence,
    Xero,
    XeroEssence,
    VengeflyKingP,
    GruzMotherP,
    FalseKnightP,
    MassiveMossChargerP,
    Hornet1P,
    GorbP,
    DungDefenderP,
    SoulWarriorP,
    BroodingMawlekP,
    OroMatoNailBrosP,
    XeroP,
    CrystalGuardianP,
    SoulMasterP,
    OblobblesP,
    MantisLordsP,
    MarmuP,
    NoskP,
    FlukemarmP,
    BrokenVesselP,
    SheoPaintmasterP,
    HiveKnightP,
    ElderHuP,
    CollectorP,
    GodTamerP,
    TroupeMasterGrimmP,
    GalienP,
    GreyPrinceZoteP,
    UumuuP,
    Hornet2P,
    SlyP,
    EnragedGuardianP,
    LostKinP,
    NoEyesP,
    TraitorLordP,
    WhiteDefenderP,
    FailedChampionP,
    MarkothP,
    WatcherKnightsP,
    SoulTyrantP,
    PureVesselP,
    NoskHornetP,
    NightmareKingGrimmP,
    Hegemol,
    Lurien,
    Monomon,
    Dreamer1,
    Dreamer2,
    Dreamer3,
    PreGrimmShop,
    SlyShopFinished,
    CanOvercharm,
    UnchainedHollowKnight,
    WatcherChandelier,
    CityGateOpen,
    PlayerDeath,
    EndingSplit,
    FlowerQuest,
    FlowerRewardGiven,
    HappyCouplePlayerDataEvent,
    NailsmithKilled,
    NightmareLantern,
    NightmareLanternDestroyed,
    HollowKnightDreamnail,
    SeerDeparts,
    SpiritGladeOpen,
    BeastsDenTrapBench,
    EternalOrdealUnlocked,
    EternalOrdealAchieved,
    ColosseumBronzeUnlocked,
    ColosseumSilverUnlocked,
    ColosseumGoldUnlocked,
    ColosseumBronze,
    ColosseumSilver,
    ColosseumGold,
    ColosseumBronzeExit,
    ColosseumSilverExit,
    ColosseumGoldExit,
    Pantheon1,
    Pantheon2,
    Pantheon3,
    Pantheon4,
    Pantheon5,
    PathOfPain,
    AspidHunter,
    Aluba,
    HuskMiner,
    GreatHopper,
    GorgeousHusk,
    MenderBug,
    killedSanctumWarrior,
    killedSoulTwister,
    MossKnight,
    MushroomBrawler,
    Zote1,
    Zote2,
    ZoteKilled,
    CrossroadsStation,
    GreenpathStation,
    QueensStationStation,
    QueensGardensStation,
    StoreroomsStation,
    KingsStationStation,
    RestingGroundsStation,
    DeepnestStation,
    HiddenStationStation,
    StagnestStation,
    MrMushroom1,
    MrMushroom2,
    MrMushroom3,
    MrMushroom4,
    MrMushroom5,
    MrMushroom6,
    MrMushroom7,
    Abyss,
    CityOfTears,
    Colosseum,
    CrystalPeak,
    Deepnest,
    DeepnestSpa,
    Dirtmouth,
    FogCanyon,
    ForgottenCrossroads,
    FungalWastes,
    Godhome,
    Greenpath,
    Hive,
    InfectedCrossroads,
    KingdomsEdge,
    QueensGardens,
    RestingGrounds,
    RoyalWaterways,
    TeachersArchive,
    WhitePalace,
    WhitePalaceSecretRoom,
    BasinEntry,
    BlueLake,
    CrystalPeakEntry,
    EnterAnyDream,
    FogCanyonEntry,
    TransGorgeousHusk,
    EnterGreenpath,
    EnterGreenpathWithOvercharm,
    TransClaw,
    TransDescendingDark,
    HiveEntry,
    KingsPass,
    KingsPassEnterFromTown,
    KingdomsEdgeEntry,
    KingdomsEdgeOvercharmedEntry,
    EnterNKG,
    QueensGardensEntry,
    QueensGardensFrogsTrans,
    QueensGardensPostArenaTransition,
    EnterSanctum,
    EnterSanctumWithShadeSoul,
    WaterwaysEntry,
    WhitePalaceEntry,
    BaldurShell,
    Dashmaster,
    DeepFocus,
    DefendersCrest,
    Dreamshield,
    DreamWielder,
    Flukenest,
    FragileGreed,
    FragileHeart,
    FragileStrength,
    FuryOfTheFallen,
    GatheringSwarm,
    GlowingWomb,
    Grimmchild,
    Grimmchild2,
    Grimmchild3,
    Grimmchild4,
    GrubberflysElegy,
    Grubsong,
    HeavyBlow,
    Hiveblood,
    JonisBlessing,
    WhiteFragmentLeft,
    WhiteFragmentRight,
    Kingsoul,
    LifebloodCore,
    LifebloodHeart,
    Longnail,
    MarkOfPride,
    NailmastersGlory,
    QuickFocus,
    QuickSlash,
    ShamanStone,
    ShapeOfUnn,
    SharpShadow,
    SoulCatcher,
    SoulEater,
    SpellTwister,
    SporeShroom,
    Sprintmaster,
    StalwartShell,
    SteadyBody,
    ThornsOfAgony,
    UnbreakableGreed,
    UnbreakableHeart,
    UnbreakableStrength,
    VoidHeart,
    WaywardCompass,
    Weaversong,
    NotchShrumalOgres,
    NotchFogCanyon,
    NotchGrimm,
    NotchSalubra1,
    NotchSalubra2,
    NotchSalubra3,
    NotchSalubra4,
    Lemm2,
    AllCharmNotchesLemm2CP,
    MetGreyMourner,
    GreyMournerSeerAscended,
    ElderbugFlower,
    givenGodseekerFlower,
    givenOroFlower,
    givenWhiteLadyFlower,
    givenEmilitiaFlower,
    BrettaRescued,
    BrummFlame,
    LittleFool,
    SlyRescued,
    Flame1,
    Flame2,
    Flame3,
    Ore1,
    Ore2,
    Ore3,
    Ore4,
    Ore5,
    Ore6,
    Grub1,
    Grub2,
    Grub3,
    Grub4,
    Grub5,
    Grub6,
    Grub7,
    Grub8,
    Grub9,
    Grub10,
    Grub11,
    Grub12,
    Grub13,
    Grub14,
    Grub15,
    Grub16,
    Grub17,
    Grub18,
    Grub19,
    Grub20,
    Grub21,
    Grub22,
    Grub23,
    Grub24,
    Grub25,
    Grub26,
    Grub27,
    Grub28,
    Grub29,
    Grub30,
    Grub31,
    Grub32,
    Grub33,
    Grub34,
    Grub35,
    Grub36,
    Grub37,
    Grub38,
    Grub39,
    Grub40,
    Grub41,
    Grub42,
    Grub43,
    Grub44,
    Grub45,
    Grub46,
    GrubBasinDive,
    GrubBasinWings,
    GrubCityBelowLoveTower,
    GrubCityBelowSanctum,
    GrubCityCollectorAll,
    GrubCityGuardHouse,
    GrubCitySanctum,
    GrubCitySpire,
    GrubCliffsBaldurShell,
    GrubCrossroadsAcid,
    GrubCrossroadsGuarded,
    GrubCrossroadsSpikes,
    GrubCrossroadsVengefly,
    GrubCrossroadsWall,
    GrubCrystalPeaksBottomLever,
    GrubCrystalPeaksCrown,
    GrubCrystalPeaksCrushers,
    GrubCrystalPeaksCrystalHeart,
    GrubCrystalPeaksMimics,
    GrubCrystalPeaksMound,
    GrubCrystalPeaksSpikes,
    GrubDeepnestBeastsDen,
    GrubDeepnestDark,
    GrubDeepnestMimics,
    GrubDeepnestNosk,
    GrubDeepnestSpikes,
    GrubFogCanyonArchives,
    GrubFungalBouncy,
    GrubFungalSporeShroom,
    GrubGreenpathCornifer,
    GrubGreenpathHunter,
    GrubGreenpathMossKnight,
    GrubGreenpathVesselFragment,
    GrubHiveExternal,
    GrubHiveInternal,
    GrubKingdomsEdgeCenter,
    GrubKingdomsEdgeOro,
    GrubQueensGardensBelowStag,
    GrubQueensGardensUpper,
    GrubQueensGardensWhiteLady,
    GrubRestingGroundsCrypts,
    GrubWaterwaysCenter,
    GrubWaterwaysHwurmps,
    GrubWaterwaysIsma,
    TreeMound,
    TreeCity,
    TreePeak,
    TreeDeepnest,
    TreeCrossroads,
    TreeLegEater,
    TreeMantisVillage,
    TreeGreenpath,
    TreeHive,
    TreeCliffs,
    TreeKingdomsEdge,
    TreeQueensGardens,
    TreeRestingGrounds,
    TreeWaterways,
    TreeGlade,
    TollBenchQG,
    TollBenchCity,
    TollBenchBasin,
    WaterwaysManhole,
    TramDeepnest,
    WhitePalaceOrb1,
    WhitePalaceOrb3,
    WhitePalaceOrb2,
    WhitePalaceLowerEntry,
    WhitePalaceLowerOrb,
    WhitePalaceLeftEntry,
    WhitePalaceLeftWingMid,
    WhitePalaceRightEntry,
    WhitePalaceRightClimb,
    WhitePalaceRightSqueeze,
    WhitePalaceRightDone,
    WhitePalaceTopEntry,
    WhitePalaceTopClimb,
    WhitePalaceTopLeverRoom,
    WhitePalaceTopLastPlats,
    WhitePalaceThroneRoom,
    WhitePalaceAtrium,
    PathOfPainEntry,
    PathOfPainTransition1,
    PathOfPainTransition2,
    PathOfPainTransition3,
    DgateKingdomsEdgeAcid,
    SoulMasterEncountered,
    GodhomeBench,
    GodhomeLoreRoom,
    Pantheon1to4Entry,
    Pantheon5Entry,
    Menu,
    MenuClaw,
    MenuGorgeousHusk,
    CorniferAtHome,
    AllSeals,
    AllEggs,
    SlySimpleKey,
    AllBreakables,
    AllUnbreakables,
    MetEmilitia,
    mapDirtmouth,
    mapCrossroads,
    mapGreenpath,
    mapFogCanyon,
    mapRoyalGardens,
    mapFungalWastes,
    mapCity,
    mapWaterways,
    mapMines,
    mapDeepnest,
    mapCliffs,
    mapOutskirts,
    mapRestingGrounds,
    mapAbyss,
    OnObtainGhostMarissa,
    OnObtainGhostCaelifFera,
    OnObtainGhostPoggy,
    OnObtainGhostGravedigger,
    OnObtainGhostJoni,
    OnObtainGhostCloth,
    OnObtainGhostVespa,
    OnObtainGhostRevek,
    OnObtainWanderersJournal,
    OnObtainHallownestSeal,
    OnObtainKingsIdol,
    OnObtainArcaneEgg,
    OnObtainRancidEgg,
    OnObtainMaskShard,
    OnObtainVesselFragment,
    OnObtainSimpleKey,
    OnUseSimpleKey,
    OnObtainGrub,
    AnyTransition,
    TransitionAfterSaveState,
    ManualSplit,
};
